// Palavras por nível de dificuldade (1 = fácil, 5 = difícil). 1000 por nível.
// Nível 5 pode ter frases de até 3 palavras.
const WORDS = {
  1: [
    'cachorro', 'gato', 'chuva', 'bola', 'cadeira', 'telefone', 'livro', 'sapato',
    'chapéu', 'relógio', 'banana', 'óculos', 'avião', 'bicicleta', 'peixe', 'cobra',
    'macaco', 'elefante', 'girafa', 'tesoura', 'escova', 'sabonete', 'martelo', 'violão',
    'tambor', 'sorvete', 'pizza', 'ovo', 'bebê', 'dinheiro', 'chave', 'cama',
    'espelho', 'tartaruga', 'borboleta', 'galinha', 'vaca', 'cavalo', 'sol', 'lua',
    'árvore', 'flor', 'carro', 'ônibus', 'barco', 'foguete', 'camiseta', 'pente',
    'bolo', 'abelha', 'coelho', 'hamster', 'periquito', 'peixinho-dourado', 'porquinho-da-índia', 'canário',
    'gerbo', 'chinchila', 'porco', 'galo', 'pato', 'ganso', 'ovelha', 'cabra',
    'boi', 'burro', 'pônei', 'peru', 'bezerro', 'mula', 'leão', 'tigre',
    'urso', 'lobo', 'raposa', 'zebra', 'gorila', 'rinoceronte', 'hipopótamo', 'canguru',
    'coala', 'panda', 'leopardo', 'jacaré', 'crocodilo', 'camelo', 'hiena', 'chita',
    'lince', 'javali', 'texugo', 'lontra', 'castor', 'esquilo', 'ouriço', 'morcego',
    'preguiça', 'baleia', 'golfinho', 'tubarão', 'polvo', 'lula', 'estrela-do-mar', 'caranguejo',
    'camarão', 'lagosta', 'foca', 'pinguim', 'água-viva', 'cavalo-marinho', 'peixe-palhaço', 'enguia',
    'arraia', 'ouriço-do-mar', 'morsa', 'orca', 'peixe-boi', 'águia', 'coruja', 'pomba',
    'pardal', 'beija-flor', 'tucano', 'papagaio', 'arara', 'avestruz', 'flamingo', 'pelicano',
    'cisne', 'corvo', 'andorinha', 'falcão', 'gavião', 'urubu', 'cegonha', 'faisão',
    'formiga', 'aranha', 'mosquito', 'mosca', 'joaninha', 'grilo', 'gafanhoto', 'barata',
    'lagarta', 'vaga-lume', 'libélula', 'escaravelho', 'pulga', 'centopeia', 'cupim', 'vespa',
    'louva-a-deus', 'traça', 'maçã', 'laranja', 'uva', 'morango', 'abacaxi', 'melancia',
    'mamão', 'manga', 'pêra', 'pêssego', 'kiwi', 'limão', 'melão', 'cereja',
    'ameixa', 'goiaba', 'caju', 'coco', 'abacate', 'framboesa', 'amora', 'romã',
    'maracujá', 'jabuticaba', 'carambola', 'lichia', 'tangerina', 'figo', 'nectarina', 'cenoura',
    'batata', 'tomate', 'alface', 'cebola', 'alho', 'pepino', 'abobrinha', 'berinjela',
    'pimentão', 'brócolis', 'couve', 'milho', 'ervilha', 'beterraba', 'mandioca', 'chuchu',
    'vagem', 'abóbora', 'rabanete', 'espinafre', 'repolho', 'quiabo', 'aspargo', 'hambúrguer',
    'sanduíche', 'pipoca', 'pão', 'queijo', 'presunto', 'salsicha', 'macarrão', 'arroz',
    'feijão', 'sopa', 'salada', 'omelete', 'panqueca', 'torta', 'biscoito', 'chocolate',
    'pudim', 'brigadeiro', 'coxinha', 'pastel', 'churrasco', 'lasanha', 'sushi', 'taco',
    'waffle', 'rosquinha', 'empadão', 'quibe', 'esfiha', 'canjica', 'pamonha', 'tapioca',
    'pão-de-queijo', 'bala', 'pirulito', 'chiclete', 'algodão-doce', 'água', 'suco', 'café',
    'chá', 'leite', 'refrigerante', 'vinho', 'cerveja', 'vitamina', 'milkshake', 'chocolate-quente',
    'limonada', 'calça', 'vestido', 'saia', 'short', 'blusa', 'casaco', 'jaqueta',
    'moletom', 'pijama', 'uniforme', 'terno', 'gravata', 'cinto', 'luva', 'cachecol',
    'touca', 'boné', 'macacão', 'colete', 'sunga', 'biquíni', 'regata', 'meia',
    'tênis', 'sandália', 'chinelo', 'bota', 'salto-alto', 'chuteira', 'sapatilha', 'pantufa',
    'colar', 'pulseira', 'anel', 'brinco', 'bolsa', 'mochila', 'carteira', 'guarda-chuva',
    'laço', 'tiara', 'gravata-borboleta', 'mesa', 'sofá', 'armário', 'estante', 'cômoda',
    'berço', 'escrivaninha', 'banco', 'rack', 'guarda-roupa', 'poltrona', 'baú', 'geladeira',
    'fogão', 'micro-ondas', 'liquidificador', 'batedeira', 'torradeira', 'ferro-de-passar', 'aspirador', 'ventilador',
    'ar-condicionado', 'máquina-de-lavar', 'cafeteira', 'secador-de-cabelo', 'panela-elétrica', 'forno', 'televisão', 'celular',
    'computador', 'tablet', 'câmera', 'controle-remoto', 'fone-de-ouvido', 'caixa-de-som', 'impressora', 'videogame',
    'carregador', 'teclado', 'mouse', 'roteador', 'pen-drive', 'piano', 'bateria', 'flauta',
    'violino', 'guitarra', 'saxofone', 'trompete', 'pandeiro', 'harpa', 'gaita', 'xilofone',
    'triângulo', 'trombone', 'acordeão', 'baixo', 'ukulele', 'cavaquinho', 'berimbau', 'chave-de-fenda',
    'alicate', 'serrote', 'furadeira', 'parafuso', 'prego', 'trena', 'machado', 'pá',
    'enxada', 'chave-inglesa', 'lixa', 'nível', 'marreta', 'caminhão', 'moto', 'navio',
    'trem', 'helicóptero', 'patinete', 'skate', 'trator', 'ambulância', 'guindaste', 'submarino',
    'jet-ski', 'teleférico', 'carroça', 'médico', 'professor', 'bombeiro', 'policial', 'cozinheiro',
    'cantor', 'ator', 'pintor', 'motorista', 'dentista', 'veterinário', 'advogado', 'engenheiro',
    'garçom', 'cabeleireiro', 'piloto', 'marinheiro', 'astronauta', 'palhaço', 'mágico', 'fotógrafo',
    'jornalista', 'juiz', 'padre', 'agricultor', 'pescador', 'carteiro', 'eletricista', 'encanador',
    'pedreiro', 'costureira', 'açougueiro', 'padeiro', 'salva-vidas', 'faxineira', 'segurança', 'recepcionista',
    'enfermeiro', 'zelador', 'apicultor', 'futebol', 'basquete', 'vôlei', 'natação', 'corrida',
    'ciclismo', 'boxe', 'judô', 'karatê', 'surfe', 'golfe', 'rúgbi', 'handebol',
    'ginástica', 'atletismo', 'patinação', 'esgrima', 'remo', 'triatlo', 'badminton', 'sinuca',
    'boliche', 'hipismo', 'caneta', 'lápis', 'borracha', 'régua', 'caderno', 'agenda',
    'grampeador', 'clipe', 'cola', 'apontador', 'calculadora', 'pasta', 'post-it', 'marcador',
    'panela', 'frigideira', 'faca', 'garfo', 'colher', 'prato', 'copo', 'xícara',
    'jarra', 'peneira', 'ralador', 'tábua', 'escumadeira', 'abridor', 'saladeira', 'bandeja',
    'funil', 'espátula', 'escova-de-dentes', 'xampu', 'escova-de-cabelo', 'toalha', 'perfume', 'creme-dental',
    'desodorante', 'cortador-de-unha', 'lâmina-de-barbear', 'fio-dental', 'boneca', 'pipa', 'ioiô', 'quebra-cabeça',
    'patins', 'carrinho', 'urso-de-pelúcia', 'bambolê', 'peão', 'bonequinho', 'bola-de-gude', 'dominó',
    'jogo-da-velha', 'lego', 'olho', 'nariz', 'boca', 'orelha', 'mão', 'pé',
    'dedo', 'joelho', 'cotovelo', 'cabeça', 'pescoço', 'ombro', 'barriga', 'coxa',
    'sobrancelha', 'queixo', 'testa', 'língua', 'dente', 'unha', 'montanha', 'rio',
    'cachoeira', 'praia', 'deserto', 'floresta', 'vulcão', 'lago', 'ilha', 'gruta',
    'vale', 'penhasco', 'duna', 'pântano', 'trovão', 'arco-íris', 'neve', 'vento',
    'furacão', 'neblina', 'geada', 'granizo', 'terremoto', 'nuvem', 'raio', 'tempestade',
    'maremoto', 'estrela', 'planeta', 'cometa', 'nave-espacial', 'buraco-negro', 'satélite', 'meteoro',
    'via-láctea', 'aniversário', 'natal', 'páscoa', 'halloween', 'carnaval', 'casamento', 'formatura',
    'réveillon', 'festa-junina', 'chá-de-bebê', 'super-herói', 'princesa', 'pirata', 'vampiro', 'fantasma',
    'bruxa', 'dragão', 'unicórnio', 'sereia', 'robô', 'zumbi', 'múmia', 'esqueleto',
    'alienígena', 'ninja', 'gigante', 'fada', 'duende', 'monstro', 'cavaleiro', 'viking',
    'cowboy', 'mago', 'sultão', 'rei', 'rainha', 'semáforo', 'ponte', 'túnel',
    'estrada', 'calçada', 'elevador', 'escada-rolante', 'porto', 'farol', 'rodoviária', 'estojo',
    'giz-de-cera', 'tinta', 'pincel', 'cartolina', 'globo-terrestre', 'quadro-negro', 'apagador', 'mapa',
    'picolé', 'bombom', 'marshmallow', 'jujuba', 'paçoca', 'cocada', 'brigadeirão', 'sonho',
    'churros', 'cupcake', 'gato grande', 'gato pequeno', 'gato gigante', 'gato minúsculo', 'cachorro grande', 'cachorro pequeno',
    'cachorro gigante', 'cachorro minúsculo', 'elefante grande', 'elefante pequeno', 'elefante gigante', 'elefante minúsculo', 'leão grande', 'leão pequeno',
    'leão gigante', 'leão minúsculo', 'urso grande', 'urso pequeno', 'urso gigante', 'urso minúsculo', 'coelho grande', 'coelho pequeno',
    'coelho gigante', 'coelho minúsculo', 'rato grande', 'rato pequeno', 'rato gigante', 'rato minúsculo', 'cavalo grande', 'cavalo pequeno',
    'cavalo gigante', 'cavalo minúsculo', 'porco grande', 'porco pequeno', 'porco gigante', 'porco minúsculo', 'pato grande', 'pato pequeno',
    'pato gigante', 'pato minúsculo', 'jacaré grande', 'jacaré pequeno', 'jacaré gigante', 'jacaré minúsculo', 'tartaruga grande', 'tartaruga pequena',
    'tartaruga gigante', 'tartaruga minúscula', 'macaco grande', 'macaco pequeno', 'macaco gigante', 'macaco minúsculo', 'girafa grande', 'girafa pequena',
    'girafa gigante', 'girafa minúscula', 'zebra grande', 'zebra pequena', 'zebra gigante', 'zebra minúscula', 'tigre grande', 'tigre pequeno',
    'tigre gigante', 'tigre minúsculo', 'lobo grande', 'lobo pequeno', 'lobo gigante', 'lobo minúsculo', 'raposa grande', 'raposa pequena',
    'raposa gigante', 'raposa minúscula', 'peixe grande', 'peixe pequeno', 'peixe gigante', 'peixe minúsculo', 'passarinho grande', 'passarinho pequeno',
    'passarinho gigante', 'passarinho minúsculo', 'bola vermelha', 'bola amarela', 'bola preta', 'bola branca', 'bola roxa', 'bola dourada',
    'bola azul', 'bola verde', 'bola rosa', 'bola laranja', 'bola marrom', 'bola cinza', 'carro vermelho', 'carro amarelo',
    'carro preto', 'carro branco', 'carro roxo', 'carro dourado', 'carro azul', 'carro verde', 'carro rosa', 'carro laranja',
    'carro marrom', 'carro cinza', 'sapato vermelho', 'sapato amarelo', 'sapato preto', 'sapato branco', 'sapato roxo', 'sapato dourado',
    'sapato azul', 'sapato verde', 'sapato rosa', 'sapato laranja', 'sapato marrom', 'sapato cinza', 'chapéu vermelho', 'chapéu amarelo',
    'chapéu preto', 'chapéu branco', 'chapéu roxo', 'chapéu dourado', 'chapéu azul', 'chapéu verde', 'chapéu rosa', 'chapéu laranja',
    'chapéu marrom', 'chapéu cinza', 'gato vermelho', 'gato amarelo', 'gato preto', 'gato branco', 'gato roxo', 'gato dourado',
    'gato azul', 'gato verde', 'gato rosa', 'gato laranja', 'gato marrom', 'gato cinza', 'cachorro vermelho', 'cachorro amarelo',
    'cachorro preto', 'cachorro branco', 'cachorro roxo', 'cachorro dourado', 'cachorro azul', 'cachorro verde', 'cachorro rosa', 'cachorro laranja',
    'cachorro marrom', 'cachorro cinza', 'flor vermelha', 'flor amarela', 'flor preta', 'flor branca', 'flor roxa', 'flor dourada',
    'flor azul', 'flor verde', 'flor rosa', 'flor laranja', 'flor marrom', 'flor cinza', 'balão vermelho', 'balão amarelo',
    'balão preto', 'balão branco', 'balão roxo', 'balão dourado', 'balão azul', 'balão verde', 'balão rosa', 'balão laranja',
    'balão marrom', 'balão cinza', 'guarda-chuva vermelho', 'guarda-chuva amarelo', 'guarda-chuva preto', 'guarda-chuva branco', 'guarda-chuva roxo', 'guarda-chuva dourado',
    'guarda-chuva azul', 'guarda-chuva verde', 'guarda-chuva rosa', 'guarda-chuva laranja', 'guarda-chuva marrom', 'guarda-chuva cinza', 'mochila vermelha', 'mochila amarela',
    'mochila preta', 'mochila branca', 'mochila roxa', 'mochila dourada', 'mochila azul', 'mochila verde', 'mochila rosa', 'mochila laranja',
    'mochila marrom', 'mochila cinza', 'boné vermelho', 'boné amarelo', 'boné preto', 'boné branco', 'boné roxo', 'boné dourado',
    'boné azul', 'boné verde', 'boné rosa', 'boné laranja', 'boné marrom', 'boné cinza', 'relógio vermelho', 'relógio amarelo',
    'relógio preto', 'relógio branco', 'relógio roxo', 'relógio dourado', 'relógio azul', 'relógio verde', 'relógio rosa', 'relógio laranja',
    'relógio marrom', 'relógio cinza', 'bicicleta vermelha', 'bicicleta amarela', 'bicicleta preta', 'bicicleta branca', 'bicicleta roxa', 'bicicleta dourada',
    'bicicleta azul', 'bicicleta verde', 'bicicleta rosa', 'bicicleta laranja', 'bicicleta marrom', 'bicicleta cinza', 'avião vermelho', 'avião amarelo',
    'avião preto', 'avião branco', 'avião roxo', 'avião dourado', 'avião azul', 'avião verde', 'avião rosa', 'avião laranja',
    'avião marrom', 'avião cinza', 'barco vermelho', 'barco amarelo', 'barco preto', 'barco branco', 'barco roxo', 'barco dourado',
    'barco azul', 'barco verde', 'barco rosa', 'barco laranja', 'barco marrom', 'barco cinza', 'pipa vermelha', 'pipa amarela',
    'pipa preta', 'pipa branca', 'pipa roxa', 'pipa dourada', 'pipa azul', 'pipa verde', 'pipa rosa', 'pipa laranja',
    'pipa marrom', 'pipa cinza', 'cadeira vermelha', 'cadeira amarela', 'cadeira preta', 'cadeira branca', 'cadeira roxa', 'cadeira dourada',
    'cadeira azul', 'cadeira verde', 'cadeira rosa', 'cadeira laranja', 'cadeira marrom', 'cadeira cinza', 'mesa vermelha', 'mesa amarela',
    'mesa preta', 'mesa branca', 'mesa roxa', 'mesa dourada', 'mesa azul', 'mesa verde', 'mesa rosa', 'mesa laranja',
    'mesa marrom', 'mesa cinza', 'copo vermelho', 'copo amarelo', 'copo preto', 'copo branco', 'copo roxo', 'copo dourado',
    'copo azul', 'copo verde', 'copo rosa', 'copo laranja', 'copo marrom', 'copo cinza', 'prato vermelho', 'prato amarelo',
    'prato preto', 'prato branco', 'prato roxo', 'prato dourado', 'prato azul', 'prato verde', 'prato rosa', 'prato laranja',
    'prato marrom', 'prato cinza', 'livro vermelho', 'livro amarelo', 'livro preto', 'livro branco', 'livro roxo', 'livro dourado',
    'livro azul', 'livro verde', 'livro rosa', 'livro laranja', 'livro marrom', 'livro cinza', 'caderno vermelho', 'caderno amarelo',
    'caderno preto', 'caderno branco', 'caderno roxo', 'caderno dourado', 'caderno azul', 'caderno verde', 'caderno rosa', 'caderno laranja',
    'caderno marrom', 'caderno cinza', 'lápis vermelho', 'lápis amarelo', 'lápis preto', 'lápis branco', 'lápis roxo', 'lápis dourado',
    'lápis azul', 'lápis verde', 'lápis rosa', 'lápis laranja', 'lápis marrom', 'lápis cinza', 'tesoura vermelha', 'tesoura amarela',
    'tesoura preta', 'tesoura branca', 'tesoura roxa', 'tesoura dourada', 'tesoura azul', 'tesoura verde', 'tesoura rosa', 'tesoura laranja',
    'tesoura marrom', 'tesoura cinza', 'colher vermelha', 'colher amarela', 'colher preta', 'colher branca', 'colher roxa', 'colher dourada',
  ],
  2: [
    'guarda-chuva', 'pescar', 'dirigir', 'nadar', 'dormir', 'cozinhar', 'dançar', 'escovar os dentes',
    'tirar foto', 'varrer', 'pular corda', 'jogar futebol', 'andar de skate', 'tomar banho', 'ler jornal', 'assistir TV',
    'tocar piano', 'cortar cabelo', 'abrir presente', 'atender telefone', 'esquiar', 'boxe', 'remar', 'cantar',
    'espirrar', 'bocejar', 'chorar', 'gargalhar', 'assobiar', 'escalar', 'mergulhar', 'pintar parede',
    'lavar carro', 'regar plantas', 'trocar lâmpada', 'andar de moto', 'jogar vôlei', 'jogar basquete', 'bater palma', 'acenar',
    'correr', 'fazer flexão', 'empinar pipa', 'surfar', 'patinar', 'martelar', 'serrar', 'costurar',
    'digitar', 'pentear cabelo', 'pular', 'voar', 'cair', 'tropeçar', 'rir', 'gritar',
    'sussurrar', 'engatinhar', 'rastejar', 'acordar', 'espreguiçar', 'soluçar', 'tossir', 'piscar',
    'aplaudir', 'sorrir', 'beijar', 'abraçar', 'apontar', 'empurrar', 'puxar', 'levantar',
    'agachar', 'equilibrar', 'malabarismo', 'cambalhota', 'flexão', 'polichinelo', 'alongamento', 'arremesso',
    'chute', 'soco', 'esgrima', 'cortar barba', 'cortar unha', 'cortar sobrancelha', 'pentear barba', 'pentear unha',
    'pentear sobrancelha', 'escovar cabelo', 'escovar barba', 'escovar unha', 'escovar sobrancelha', 'arrumar cabelo', 'arrumar barba', 'arrumar unha',
    'arrumar sobrancelha', 'lavar cabelo', 'lavar barba', 'lavar unha', 'lavar sobrancelha', 'secar cabelo', 'secar barba', 'secar unha',
    'secar sobrancelha', 'lavar roupa', 'lavar toalha', 'lavar lençol', 'lavar camisa', 'lavar calça', 'lavar meia', 'lavar casaco',
    'lavar uniforme', 'secar roupa', 'secar toalha', 'secar lençol', 'secar camisa', 'secar calça', 'secar meia', 'secar casaco',
    'secar uniforme', 'dobrar roupa', 'dobrar toalha', 'dobrar lençol', 'dobrar camisa', 'dobrar calça', 'dobrar meia', 'dobrar casaco',
    'dobrar uniforme', 'pendurar roupa', 'pendurar toalha', 'pendurar lençol', 'pendurar camisa', 'pendurar calça', 'pendurar meia', 'pendurar casaco',
    'pendurar uniforme', 'passar roupa', 'passar toalha', 'passar lençol', 'passar camisa', 'passar calça', 'passar meia', 'passar casaco',
    'passar uniforme', 'guardar roupa', 'guardar toalha', 'guardar lençol', 'guardar camisa', 'guardar calça', 'guardar meia', 'guardar casaco',
    'guardar uniforme', 'vestir roupa', 'vestir toalha', 'vestir lençol', 'vestir camisa', 'vestir calça', 'vestir meia', 'vestir casaco',
    'vestir uniforme', 'tirar roupa', 'tirar toalha', 'tirar lençol', 'tirar camisa', 'tirar calça', 'tirar meia', 'tirar casaco',
    'tirar uniforme', 'lavar prato', 'lavar copo', 'lavar talher', 'lavar panela', 'lavar xícara', 'lavar garrafa', 'lavar frigideira',
    'secar prato', 'secar copo', 'secar talher', 'secar panela', 'secar xícara', 'secar garrafa', 'secar frigideira', 'guardar prato',
    'guardar copo', 'guardar talher', 'guardar panela', 'guardar xícara', 'guardar garrafa', 'guardar frigideira', 'quebrar prato', 'quebrar copo',
    'quebrar talher', 'quebrar panela', 'quebrar xícara', 'quebrar garrafa', 'quebrar frigideira', 'encontrar prato', 'encontrar copo', 'encontrar talher',
    'encontrar panela', 'encontrar xícara', 'encontrar garrafa', 'encontrar frigideira', 'procurar prato', 'procurar copo', 'procurar talher', 'procurar panela',
    'procurar xícara', 'procurar garrafa', 'procurar frigideira', 'derrubar prato', 'derrubar copo', 'derrubar talher', 'derrubar panela', 'derrubar xícara',
    'derrubar garrafa', 'derrubar frigideira', 'empilhar prato', 'empilhar copo', 'empilhar talher', 'empilhar panela', 'empilhar xícara', 'empilhar garrafa',
    'empilhar frigideira', 'cortar batata', 'cortar cebola', 'cortar cenoura', 'cortar tomate', 'cortar fruta', 'cortar legume', 'cortar carne',
    'cortar peixe', 'cortar ovo', 'cortar massa', 'cortar arroz', 'cortar feijão', 'cortar bolo', 'cortar pão', 'descascar batata',
    'descascar cebola', 'descascar cenoura', 'descascar tomate', 'descascar fruta', 'descascar legume', 'descascar carne', 'descascar peixe', 'descascar ovo',
    'descascar massa', 'descascar arroz', 'descascar feijão', 'descascar bolo', 'descascar pão', 'ralar batata', 'ralar cebola', 'ralar cenoura',
    'ralar tomate', 'ralar fruta', 'ralar legume', 'ralar carne', 'ralar peixe', 'ralar ovo', 'ralar massa', 'ralar arroz',
    'ralar feijão', 'ralar bolo', 'ralar pão', 'picar batata', 'picar cebola', 'picar cenoura', 'picar tomate', 'picar fruta',
    'picar legume', 'picar carne', 'picar peixe', 'picar ovo', 'picar massa', 'picar arroz', 'picar feijão', 'picar bolo',
    'picar pão', 'temperar batata', 'temperar cebola', 'temperar cenoura', 'temperar tomate', 'temperar fruta', 'temperar legume', 'temperar carne',
    'temperar peixe', 'temperar ovo', 'temperar massa', 'temperar arroz', 'temperar feijão', 'temperar bolo', 'temperar pão', 'provar batata',
    'provar cebola', 'provar cenoura', 'provar tomate', 'provar fruta', 'provar legume', 'provar carne', 'provar peixe', 'provar ovo',
    'provar massa', 'provar arroz', 'provar feijão', 'provar bolo', 'provar pão', 'cheirar batata', 'cheirar cebola', 'cheirar cenoura',
    'cheirar tomate', 'cheirar fruta', 'cheirar legume', 'cheirar carne', 'cheirar peixe', 'cheirar ovo', 'cheirar massa', 'cheirar arroz',
    'cheirar feijão', 'cheirar bolo', 'cheirar pão', 'fritar batata', 'fritar cebola', 'fritar cenoura', 'fritar tomate', 'fritar fruta',
    'fritar legume', 'fritar carne', 'fritar peixe', 'fritar ovo', 'fritar massa', 'fritar arroz', 'fritar feijão', 'fritar bolo',
    'fritar pão', 'assar batata', 'assar cebola', 'assar cenoura', 'assar tomate', 'assar fruta', 'assar legume', 'assar carne',
    'assar peixe', 'assar ovo', 'assar massa', 'assar arroz', 'assar feijão', 'assar bolo', 'assar pão', 'cozinhar batata',
    'cozinhar cebola', 'cozinhar cenoura', 'cozinhar tomate', 'cozinhar fruta', 'cozinhar legume', 'cozinhar carne', 'cozinhar peixe', 'cozinhar ovo',
    'cozinhar massa', 'cozinhar arroz', 'cozinhar feijão', 'cozinhar bolo', 'cozinhar pão', 'misturar batata', 'misturar cebola', 'misturar cenoura',
    'misturar tomate', 'misturar fruta', 'misturar legume', 'misturar carne', 'misturar peixe', 'misturar ovo', 'misturar massa', 'misturar arroz',
    'misturar feijão', 'misturar bolo', 'misturar pão', 'servir batata', 'servir cebola', 'servir cenoura', 'servir tomate', 'servir fruta',
    'servir legume', 'servir carne', 'servir peixe', 'servir ovo', 'servir massa', 'servir arroz', 'servir feijão', 'servir bolo',
    'servir pão', 'consertar cadeira', 'consertar mesa', 'consertar estante', 'consertar armário', 'consertar porta', 'consertar janela', 'consertar prateleira',
    'consertar bicicleta', 'consertar pneu', 'consertar parede', 'montar cadeira', 'montar mesa', 'montar estante', 'montar armário', 'montar porta',
    'montar janela', 'montar prateleira', 'montar bicicleta', 'montar pneu', 'montar parede', 'desmontar cadeira', 'desmontar mesa', 'desmontar estante',
    'desmontar armário', 'desmontar porta', 'desmontar janela', 'desmontar prateleira', 'desmontar bicicleta', 'desmontar pneu', 'desmontar parede', 'apertar cadeira',
    'apertar mesa', 'apertar estante', 'apertar armário', 'apertar porta', 'apertar janela', 'apertar prateleira', 'apertar bicicleta', 'apertar pneu',
    'apertar parede', 'furar cadeira', 'furar mesa', 'furar estante', 'furar armário', 'furar porta', 'furar janela', 'furar prateleira',
    'furar bicicleta', 'furar pneu', 'furar parede', 'martelar cadeira', 'martelar mesa', 'martelar estante', 'martelar armário', 'martelar porta',
    'martelar janela', 'martelar prateleira', 'martelar bicicleta', 'martelar pneu', 'martelar parede', 'serrar cadeira', 'serrar mesa', 'serrar estante',
    'serrar armário', 'serrar porta', 'serrar janela', 'serrar prateleira', 'serrar bicicleta', 'serrar pneu', 'serrar parede', 'lixar cadeira',
    'lixar mesa', 'lixar estante', 'lixar armário', 'lixar porta', 'lixar janela', 'lixar prateleira', 'lixar bicicleta', 'lixar pneu',
    'lixar parede', 'medir cadeira', 'medir mesa', 'medir estante', 'medir armário', 'medir porta', 'medir janela', 'medir prateleira',
    'medir bicicleta', 'medir pneu', 'medir parede', 'pintar cadeira', 'pintar mesa', 'pintar estante', 'pintar armário', 'pintar porta',
    'pintar janela', 'pintar prateleira', 'pintar bicicleta', 'pintar pneu', 'ligar celular', 'ligar computador', 'ligar televisão', 'ligar câmera',
    'ligar videogame', 'ligar impressora', 'ligar tablet', 'ligar rádio', 'desligar celular', 'desligar computador', 'desligar televisão', 'desligar câmera',
    'desligar videogame', 'desligar impressora', 'desligar tablet', 'desligar rádio', 'carregar celular', 'carregar computador', 'carregar televisão', 'carregar câmera',
    'carregar videogame', 'carregar impressora', 'carregar tablet', 'carregar rádio', 'tocar celular', 'tocar computador', 'tocar televisão', 'tocar câmera',
    'tocar videogame', 'tocar impressora', 'tocar tablet', 'tocar rádio', 'filmar celular', 'filmar computador', 'filmar televisão', 'filmar câmera',
    'filmar videogame', 'filmar impressora', 'filmar tablet', 'filmar rádio', 'tirar foto de celular', 'tirar foto de computador', 'tirar foto de televisão', 'tirar foto de câmera',
    'tirar foto de videogame', 'tirar foto de impressora', 'tirar foto de tablet', 'tirar foto de rádio', 'digitar em celular', 'digitar em computador', 'digitar em televisão', 'digitar em câmera',
    'digitar em videogame', 'digitar em impressora', 'digitar em tablet', 'digitar em rádio', 'imprimir celular', 'imprimir computador', 'imprimir televisão', 'imprimir câmera',
    'imprimir videogame', 'imprimir impressora', 'imprimir tablet', 'imprimir rádio', 'configurar celular', 'configurar computador', 'configurar televisão', 'configurar câmera',
    'configurar videogame', 'configurar impressora', 'configurar tablet', 'configurar rádio', 'regar planta', 'regar flor', 'regar grama', 'regar árvore',
    'regar horta', 'regar arbusto', 'plantar planta', 'plantar flor', 'plantar grama', 'plantar árvore', 'plantar horta', 'plantar arbusto',
    'colher planta', 'colher flor', 'colher grama', 'colher árvore', 'colher horta', 'colher arbusto', 'podar planta', 'podar flor',
    'podar grama', 'podar árvore', 'podar horta', 'podar arbusto', 'cortar planta', 'cortar flor', 'cortar grama', 'cortar árvore',
    'cortar horta', 'cortar arbusto', 'procurar chave', 'procurar mala', 'procurar caixa', 'procurar presente', 'procurar livro', 'procurar bola',
    'procurar sapato', 'procurar guarda-chuva', 'procurar mochila', 'procurar carrinho', 'procurar brinquedo', 'procurar bilhete', 'encontrar chave', 'encontrar mala',
    'encontrar caixa', 'encontrar presente', 'encontrar livro', 'encontrar bola', 'encontrar sapato', 'encontrar guarda-chuva', 'encontrar mochila', 'encontrar carrinho',
    'encontrar brinquedo', 'encontrar bilhete', 'perder chave', 'perder mala', 'perder caixa', 'perder presente', 'perder livro', 'perder bola',
    'perder sapato', 'perder guarda-chuva', 'perder mochila', 'perder carrinho', 'perder brinquedo', 'perder bilhete', 'guardar chave', 'guardar mala',
    'guardar caixa', 'guardar presente', 'guardar livro', 'guardar bola', 'guardar sapato', 'guardar guarda-chuva', 'guardar mochila', 'guardar carrinho',
    'guardar brinquedo', 'guardar bilhete', 'carregar chave', 'carregar mala', 'carregar caixa', 'carregar presente', 'carregar livro', 'carregar bola',
    'carregar sapato', 'carregar guarda-chuva', 'carregar mochila', 'carregar carrinho', 'carregar brinquedo', 'carregar bilhete', 'empurrar chave', 'empurrar mala',
    'empurrar caixa', 'empurrar presente', 'empurrar livro', 'empurrar bola', 'empurrar sapato', 'empurrar guarda-chuva', 'empurrar mochila', 'empurrar carrinho',
    'empurrar brinquedo', 'empurrar bilhete', 'puxar chave', 'puxar mala', 'puxar caixa', 'puxar presente', 'puxar livro', 'puxar bola',
    'puxar sapato', 'puxar guarda-chuva', 'puxar mochila', 'puxar carrinho', 'puxar brinquedo', 'puxar bilhete', 'abrir chave', 'abrir mala',
    'abrir caixa', 'abrir livro', 'abrir bola', 'abrir sapato', 'abrir guarda-chuva', 'abrir mochila', 'abrir carrinho', 'abrir brinquedo',
    'abrir bilhete', 'fechar chave', 'fechar mala', 'fechar caixa', 'fechar presente', 'fechar livro', 'fechar bola', 'fechar sapato',
    'fechar guarda-chuva', 'fechar mochila', 'fechar carrinho', 'fechar brinquedo', 'fechar bilhete', 'enrolar chave', 'enrolar mala', 'enrolar caixa',
    'enrolar presente', 'enrolar livro', 'enrolar bola', 'enrolar sapato', 'enrolar guarda-chuva', 'enrolar mochila', 'enrolar carrinho', 'enrolar brinquedo',
    'enrolar bilhete', 'embrulhar chave', 'embrulhar mala', 'embrulhar caixa', 'embrulhar presente', 'embrulhar livro', 'embrulhar bola', 'embrulhar sapato',
    'embrulhar guarda-chuva', 'embrulhar mochila', 'embrulhar carrinho', 'embrulhar brinquedo', 'embrulhar bilhete', 'pendurar chave', 'pendurar mala', 'pendurar caixa',
    'pendurar presente', 'pendurar livro', 'pendurar bola', 'pendurar sapato', 'pendurar guarda-chuva', 'pendurar mochila', 'pendurar carrinho', 'pendurar brinquedo',
    'pendurar bilhete', 'quebrar chave', 'quebrar mala', 'quebrar caixa', 'quebrar presente', 'quebrar livro', 'quebrar bola', 'quebrar sapato',
    'quebrar guarda-chuva', 'quebrar mochila', 'quebrar carrinho', 'quebrar brinquedo', 'quebrar bilhete', 'derrubar chave', 'derrubar mala', 'derrubar caixa',
    'derrubar presente', 'derrubar livro', 'derrubar bola', 'derrubar sapato', 'derrubar guarda-chuva', 'derrubar mochila', 'derrubar carrinho', 'derrubar brinquedo',
    'derrubar bilhete', 'esconder chave', 'esconder mala', 'esconder caixa', 'esconder presente', 'esconder livro', 'esconder bola', 'esconder sapato',
    'esconder guarda-chuva', 'esconder mochila', 'esconder carrinho', 'esconder brinquedo', 'esconder bilhete', 'chutar bola', 'chutar peteca', 'chutar bumerangue',
    'chutar frisbee', 'arremessar bola', 'arremessar peteca', 'arremessar bumerangue', 'arremessar frisbee', 'driblar bola', 'driblar peteca', 'driblar bumerangue',
    'driblar frisbee', 'rebater bola', 'rebater peteca', 'rebater bumerangue', 'rebater frisbee', 'sacar bola', 'sacar peteca', 'sacar bumerangue',
    'sacar frisbee', 'quicar bola', 'quicar peteca', 'quicar bumerangue', 'quicar frisbee', 'dirigir carro', 'dirigir moto', 'dirigir bicicleta',
    'dirigir caminhão', 'dirigir ônibus', 'dirigir trator', 'estacionar carro', 'estacionar moto', 'estacionar bicicleta', 'estacionar caminhão', 'estacionar ônibus',
    'estacionar trator', 'lavar moto', 'lavar bicicleta', 'lavar caminhão', 'lavar ônibus', 'lavar trator', 'abastecer carro', 'abastecer moto',
    'abastecer bicicleta', 'abastecer caminhão', 'abastecer ônibus', 'abastecer trator', 'consertar carro', 'consertar moto', 'consertar caminhão', 'consertar ônibus',
    'consertar trator', 'empurrar carro', 'empurrar moto', 'empurrar bicicleta', 'empurrar caminhão', 'empurrar ônibus', 'empurrar trator', 'alimentar cachorro',
    'alimentar gato', 'alimentar coelho', 'alimentar passarinho', 'alimentar cavalo', 'alimentar peixe', 'pentear cachorro', 'pentear gato', 'pentear coelho',
    'pentear passarinho', 'pentear cavalo', 'pentear peixe', 'passear com cachorro', 'passear com gato', 'passear com coelho', 'passear com passarinho', 'passear com cavalo',
    'passear com peixe', 'dar banho em cachorro', 'dar banho em gato', 'dar banho em coelho', 'dar banho em passarinho', 'dar banho em cavalo', 'dar banho em peixe', 'brincar com cachorro',
    'brincar com gato', 'brincar com coelho', 'brincar com passarinho', 'brincar com cavalo', 'brincar com peixe', 'treinar cachorro', 'treinar gato', 'treinar coelho',
    'treinar passarinho', 'treinar cavalo', 'treinar peixe', 'tocar violão', 'tocar bateria', 'tocar flauta', 'tocar violino', 'tocar guitarra',
    'tocar saxofone', 'tocar trompete', 'afinar violão', 'afinar piano', 'afinar bateria', 'afinar flauta', 'afinar violino', 'afinar guitarra',
    'afinar saxofone', 'afinar trompete', 'guardar violão', 'guardar piano', 'guardar bateria', 'guardar flauta', 'guardar violino', 'guardar guitarra',
    'guardar saxofone', 'guardar trompete', 'carregar violão', 'carregar piano', 'carregar bateria', 'carregar flauta', 'carregar violino', 'carregar guitarra',
    'carregar saxofone', 'carregar trompete', 'comprar violão', 'comprar piano', 'comprar bateria', 'comprar flauta', 'comprar violino', 'comprar guitarra',
    'comprar saxofone', 'comprar trompete', 'aprender a tocar violão', 'aprender a tocar piano', 'aprender a tocar bateria', 'aprender a tocar flauta', 'aprender a tocar violino', 'aprender a tocar guitarra',
    'aprender a tocar saxofone', 'aprender a tocar trompete', 'jogar tênis', 'jogar handebol', 'jogar rúgbi', 'jogar golfe', 'jogar boxe', 'praticar futebol',
    'praticar vôlei', 'praticar basquete', 'praticar tênis', 'praticar handebol', 'praticar rúgbi', 'praticar golfe', 'praticar boxe', 'assistir futebol',
    'assistir vôlei', 'assistir basquete', 'assistir tênis', 'assistir handebol', 'assistir rúgbi', 'assistir golfe', 'assistir boxe', 'comentar futebol',
    'comentar vôlei', 'comentar basquete', 'comentar tênis', 'comentar handebol', 'comentar rúgbi', 'comentar golfe', 'comentar boxe', 'treinar futebol',
    'treinar vôlei', 'treinar basquete', 'treinar tênis', 'treinar handebol', 'treinar rúgbi', 'treinar golfe', 'treinar boxe', 'comprar presente',
    'comprar roupa', 'comprar sapato', 'comprar livro', 'comprar brinquedo', 'comprar celular', 'vender presente', 'vender roupa', 'vender sapato',
    'vender livro', 'vender brinquedo', 'vender celular', 'trocar presente', 'trocar roupa', 'trocar sapato', 'trocar livro', 'trocar brinquedo',
    'trocar celular', 'devolver presente', 'devolver roupa', 'devolver sapato', 'devolver livro', 'devolver brinquedo', 'devolver celular', 'embrulhar roupa',
    'embrulhar celular', 'pagar presente', 'pagar roupa', 'pagar sapato', 'pagar livro', 'pagar brinquedo', 'pagar celular', 'escolher presente',
    'escolher roupa', 'escolher sapato', 'escolher livro', 'escolher brinquedo', 'escolher celular', 'varrer chão', 'varrer tapete', 'varrer sofá',
    'varrer cama', 'varrer quarto', 'varrer cozinha', 'varrer banheiro', 'varrer sala', 'varrer garagem', 'varrer quintal', 'esfregar chão',
  ],
  3: [
    'lavar louça', 'cinema', 'dentista', 'aeroporto', 'praia', 'academia', 'supermercado', 'hospital',
    'casamento', 'escola', 'estádio', 'shopping', 'churrasco', 'acampamento', 'trocar pneu', 'montar móvel',
    'fazer compras', 'pedir pizza', 'esperar elevador', 'cortar grama', 'passear com cachorro', 'dar banho no cachorro', 'fazer as unhas', 'arrumar a mala',
    'passar roupa', 'estacionar carro', 'trocar fralda', 'assar bolo', 'fritar ovo', 'fazer café', 'montanha-russa', 'jogar videogame',
    'tirar selfie', 'circo', 'zoológico', 'igreja', 'restaurante', 'padaria', 'salão de beleza', 'posto de gasolina',
    'karaokê', 'balada', 'pescaria', 'piquenique', 'maratona', 'ginástica olímpica', 'jogar xadrez', 'jogar sinuca',
    'fazer pipoca', 'andar de patinete', 'biblioteca', 'museu', 'parque', 'farmácia', 'banco', 'correio',
    'delegacia', 'feira', 'açougue', 'oficina mecânica', 'lavanderia', 'pet shop', 'floricultura', 'sorveteria',
    'lanchonete', 'consultório', 'cartório', 'rodoviária', 'metrô', 'praça', 'parque de diversões', 'aquário',
    'planetário', 'hotel', 'motel', 'drive-thru', 'feira livre', 'mercadinho', 'drogaria', 'ótica',
    'cemitério', 'quartel', 'universidade', 'creche', 'fórum', 'prefeitura', 'ginásio', 'quadra poliesportiva',
    'clube', 'spa', 'sauna', 'boate', 'bar', 'pub', 'confeitaria', 'hamburgueria',
    'pizzaria', 'churrascaria', 'sushi bar', 'food truck', 'camping', 'pousada', 'resort', 'teatro',
    'ópera', 'galeria de arte', 'livraria', 'papelaria', 'loja de roupas', 'loja de brinquedos', 'loja de eletrônicos', 'concessionária',
    'borracharia', 'autoescola', 'academia de luta', 'piscina pública', 'quadra de tênis', 'campo de golfe', 'pista de skate', 'pista de atletismo',
    'arena', 'castelo', 'palácio', 'catedral', 'templo', 'torre', 'farol', 'cais',
    'marina', 'mina', 'fazenda', 'sítio', 'vinícola', 'cervejaria', 'fábrica', 'usina',
    'base militar', 'estação espacial', 'laboratório', 'escritório', 'coworking', 'call center', 'estúdio de gravação', 'estúdio de tatuagem',
    'barbearia', 'clínica veterinária', 'canil', 'abrigo de animais', 'reserva florestal', 'parque nacional', 'trilha', 'mirante',
    'praça de alimentação', 'feira de artesanato', 'mercado municipal', 'feira de rua', 'antiquário', 'brechó', 'sebo', 'bazar',
    'leilão', 'fazer compras no mercado', 'trocar de roupa', 'marcar consulta', 'cancelar reserva', 'pagar conta no restaurante', 'esperar mesa no restaurante', 'escolher roupa na loja',
    'provar roupa no shopping', 'pegar fila no banco', 'sacar dinheiro no caixa eletrônico', 'depositar cheque', 'abrir conta no banco', 'enviar carta no correio', 'retirar encomenda no correio', 'comprar selo',
    'comprar remédio na farmácia', 'pegar receita médica', 'fazer exame de sangue', 'tirar radiografia', 'visitar paciente no hospital', 'doar sangue', 'tomar vacina', 'fazer consulta odontológica',
    'extrair dente', 'fazer limpeza de pele', 'cortar cabelo no salão', 'fazer escova no salão', 'pintar cabelo', 'fazer manicure', 'fazer pedicure', 'fazer massagem',
    'bronzear na praia', 'construir castelo de areia', 'jogar frescobol na praia', 'surfar na praia', 'nadar no mar', 'tomar sorvete na praia', 'andar de caiaque', 'andar a cavalo',
    'visitar fazenda', 'colher frutas no pomar', 'ordenhar vaca', 'plantar horta', 'colher legumes', 'alimentar galinhas', 'assistir show', 'comprar ingresso para show',
    'esperar fila do show', 'tirar foto com artista', 'pedir autógrafo', 'assistir peça de teatro', 'aplaudir no teatro', 'assistir balé', 'dançar em festa', 'brindar em festa',
    'cantar parabéns', 'soprar velas', 'abrir presente de aniversário', 'decorar bolo', 'servir bolo', 'distribuir docinhos', 'montar decoração de festa', 'contratar animador de festa',
    'organizar chá de bebê', 'fazer ensaio fotográfico', 'tirar foto de casamento', 'jogar buquê no casamento', 'dançar valsa no casamento', 'brindar no casamento', 'visitar cinema', 'visitar dentista',
    'visitar aeroporto', 'visitar praia', 'visitar academia', 'visitar supermercado', 'visitar hospital', 'visitar escola', 'visitar estádio', 'visitar shopping',
    'visitar zoológico', 'visitar igreja', 'visitar restaurante', 'visitar padaria', 'visitar salão de beleza', 'visitar posto de gasolina', 'visitar biblioteca', 'visitar museu',
    'visitar parque', 'visitar farmácia', 'visitar banco', 'visitar correio', 'visitar delegacia', 'visitar feira', 'visitar açougue', 'visitar oficina mecânica',
    'visitar lavanderia', 'visitar pet shop', 'visitar floricultura', 'visitar sorveteria', 'visitar lanchonete', 'visitar consultório', 'visitar cartório', 'visitar rodoviária',
    'visitar metrô', 'visitar praça', 'visitar circo', 'visitar parque de diversões', 'visitar aquário', 'visitar planetário', 'visitar hotel', 'visitar motel',
    'visitar drive-thru', 'visitar feira livre', 'visitar mercadinho', 'visitar drogaria', 'visitar ótica', 'visitar cemitério', 'visitar quartel', 'visitar universidade',
    'visitar creche', 'visitar fórum', 'visitar prefeitura', 'visitar ginásio', 'visitar quadra poliesportiva', 'visitar clube', 'visitar spa', 'visitar sauna',
    'visitar boate', 'visitar bar', 'visitar pub', 'visitar confeitaria', 'visitar hamburgueria', 'visitar pizzaria', 'visitar churrascaria', 'visitar sushi bar',
    'visitar food truck', 'visitar camping', 'visitar pousada', 'visitar resort', 'visitar teatro', 'visitar ópera', 'visitar galeria de arte', 'visitar livraria',
    'visitar papelaria', 'visitar loja de roupas', 'visitar loja de brinquedos', 'visitar loja de eletrônicos', 'visitar concessionária', 'visitar borracharia', 'visitar autoescola', 'visitar academia de luta',
    'visitar piscina pública', 'visitar quadra de tênis', 'visitar campo de golfe', 'visitar pista de skate', 'visitar pista de atletismo', 'visitar arena', 'visitar castelo', 'visitar palácio',
    'visitar catedral', 'visitar templo', 'visitar torre', 'visitar farol', 'visitar cais', 'visitar marina', 'visitar mina', 'visitar sítio',
    'visitar vinícola', 'visitar cervejaria', 'visitar fábrica', 'visitar usina', 'visitar base militar', 'visitar estação espacial', 'visitar laboratório', 'visitar escritório',
    'visitar coworking', 'visitar call center', 'visitar estúdio de gravação', 'visitar estúdio de tatuagem', 'visitar barbearia', 'visitar clínica veterinária', 'visitar canil', 'visitar abrigo de animais',
    'visitar reserva florestal', 'visitar parque nacional', 'visitar trilha', 'visitar mirante', 'visitar praça de alimentação', 'visitar feira de artesanato', 'visitar mercado municipal', 'visitar feira de rua',
    'visitar antiquário', 'visitar brechó', 'visitar sebo', 'visitar bazar', 'visitar leilão', 'conhecer cinema', 'conhecer dentista', 'conhecer aeroporto',
    'conhecer praia', 'conhecer academia', 'conhecer supermercado', 'conhecer hospital', 'conhecer escola', 'conhecer estádio', 'conhecer shopping', 'conhecer zoológico',
    'conhecer igreja', 'conhecer restaurante', 'conhecer padaria', 'conhecer salão de beleza', 'conhecer posto de gasolina', 'conhecer biblioteca', 'conhecer museu', 'conhecer parque',
    'conhecer farmácia', 'conhecer banco', 'conhecer correio', 'conhecer delegacia', 'conhecer feira', 'conhecer açougue', 'conhecer oficina mecânica', 'conhecer lavanderia',
    'conhecer pet shop', 'conhecer floricultura', 'conhecer sorveteria', 'conhecer lanchonete', 'conhecer consultório', 'conhecer cartório', 'conhecer rodoviária', 'conhecer metrô',
    'conhecer praça', 'conhecer circo', 'conhecer parque de diversões', 'conhecer aquário', 'conhecer planetário', 'conhecer hotel', 'conhecer motel', 'conhecer drive-thru',
    'conhecer feira livre', 'conhecer mercadinho', 'conhecer drogaria', 'conhecer ótica', 'conhecer cemitério', 'conhecer quartel', 'conhecer universidade', 'conhecer creche',
    'conhecer fórum', 'conhecer prefeitura', 'conhecer ginásio', 'conhecer quadra poliesportiva', 'conhecer clube', 'conhecer spa', 'conhecer sauna', 'conhecer boate',
    'conhecer bar', 'conhecer pub', 'conhecer confeitaria', 'conhecer hamburgueria', 'conhecer pizzaria', 'conhecer churrascaria', 'conhecer sushi bar', 'conhecer food truck',
    'conhecer camping', 'conhecer pousada', 'conhecer resort', 'conhecer teatro', 'conhecer ópera', 'conhecer galeria de arte', 'conhecer livraria', 'conhecer papelaria',
    'conhecer loja de roupas', 'conhecer loja de brinquedos', 'conhecer loja de eletrônicos', 'conhecer concessionária', 'conhecer borracharia', 'conhecer autoescola', 'conhecer academia de luta', 'conhecer piscina pública',
    'conhecer quadra de tênis', 'conhecer campo de golfe', 'conhecer pista de skate', 'conhecer pista de atletismo', 'conhecer arena', 'conhecer castelo', 'conhecer palácio', 'conhecer catedral',
    'conhecer templo', 'conhecer torre', 'conhecer farol', 'conhecer cais', 'conhecer marina', 'conhecer mina', 'conhecer fazenda', 'conhecer sítio',
    'conhecer vinícola', 'conhecer cervejaria', 'conhecer fábrica', 'conhecer usina', 'conhecer base militar', 'conhecer estação espacial', 'conhecer laboratório', 'conhecer escritório',
    'conhecer coworking', 'conhecer call center', 'conhecer estúdio de gravação', 'conhecer estúdio de tatuagem', 'conhecer barbearia', 'conhecer clínica veterinária', 'conhecer canil', 'conhecer abrigo de animais',
    'conhecer reserva florestal', 'conhecer parque nacional', 'conhecer trilha', 'conhecer mirante', 'conhecer praça de alimentação', 'conhecer feira de artesanato', 'conhecer mercado municipal', 'conhecer feira de rua',
    'conhecer antiquário', 'conhecer brechó', 'conhecer sebo', 'conhecer bazar', 'conhecer leilão', 'fechar cinema', 'fechar dentista', 'fechar aeroporto',
    'fechar praia', 'fechar academia', 'fechar supermercado', 'fechar hospital', 'fechar escola', 'fechar estádio', 'fechar shopping', 'fechar zoológico',
    'fechar igreja', 'fechar restaurante', 'fechar padaria', 'fechar salão de beleza', 'fechar posto de gasolina', 'fechar biblioteca', 'fechar museu', 'fechar parque',
    'fechar farmácia', 'fechar banco', 'fechar correio', 'fechar delegacia', 'fechar feira', 'fechar açougue', 'fechar oficina mecânica', 'fechar lavanderia',
    'fechar pet shop', 'fechar floricultura', 'fechar sorveteria', 'fechar lanchonete', 'fechar consultório', 'fechar cartório', 'fechar rodoviária', 'fechar metrô',
    'fechar praça', 'fechar circo', 'fechar parque de diversões', 'fechar aquário', 'fechar planetário', 'fechar hotel', 'fechar motel', 'fechar drive-thru',
    'fechar feira livre', 'fechar mercadinho', 'fechar drogaria', 'fechar ótica', 'fechar cemitério', 'fechar quartel', 'fechar universidade', 'fechar creche',
    'fechar fórum', 'fechar prefeitura', 'fechar ginásio', 'fechar quadra poliesportiva', 'fechar clube', 'fechar spa', 'fechar sauna', 'fechar boate',
    'fechar bar', 'fechar pub', 'fechar confeitaria', 'fechar hamburgueria', 'fechar pizzaria', 'fechar churrascaria', 'fechar sushi bar', 'fechar food truck',
    'fechar camping', 'fechar pousada', 'fechar resort', 'fechar teatro', 'fechar ópera', 'fechar galeria de arte', 'fechar livraria', 'fechar papelaria',
    'fechar loja de roupas', 'fechar loja de brinquedos', 'fechar loja de eletrônicos', 'fechar concessionária', 'fechar borracharia', 'fechar autoescola', 'fechar academia de luta', 'fechar piscina pública',
    'fechar quadra de tênis', 'fechar campo de golfe', 'fechar pista de skate', 'fechar pista de atletismo', 'fechar arena', 'fechar castelo', 'fechar palácio', 'fechar catedral',
    'fechar templo', 'fechar torre', 'fechar farol', 'fechar cais', 'fechar marina', 'fechar mina', 'fechar fazenda', 'fechar sítio',
    'fechar vinícola', 'fechar cervejaria', 'fechar fábrica', 'fechar usina', 'fechar base militar', 'fechar estação espacial', 'fechar laboratório', 'fechar escritório',
    'fechar coworking', 'fechar call center', 'fechar estúdio de gravação', 'fechar estúdio de tatuagem', 'fechar barbearia', 'fechar clínica veterinária', 'fechar canil', 'fechar abrigo de animais',
    'fechar reserva florestal', 'fechar parque nacional', 'fechar trilha', 'fechar mirante', 'fechar praça de alimentação', 'fechar feira de artesanato', 'fechar mercado municipal', 'fechar feira de rua',
    'fechar antiquário', 'fechar brechó', 'fechar sebo', 'fechar bazar', 'fechar leilão', 'abrir cinema', 'abrir dentista', 'abrir aeroporto',
    'abrir praia', 'abrir academia', 'abrir supermercado', 'abrir hospital', 'abrir escola', 'abrir estádio', 'abrir shopping', 'abrir zoológico',
    'abrir igreja', 'abrir restaurante', 'abrir padaria', 'abrir salão de beleza', 'abrir posto de gasolina', 'abrir biblioteca', 'abrir museu', 'abrir parque',
    'abrir farmácia', 'abrir banco', 'abrir correio', 'abrir delegacia', 'abrir feira', 'abrir açougue', 'abrir oficina mecânica', 'abrir lavanderia',
    'abrir pet shop', 'abrir floricultura', 'abrir sorveteria', 'abrir lanchonete', 'abrir consultório', 'abrir cartório', 'abrir rodoviária', 'abrir metrô',
    'abrir praça', 'abrir circo', 'abrir parque de diversões', 'abrir aquário', 'abrir planetário', 'abrir hotel', 'abrir motel', 'abrir drive-thru',
    'abrir feira livre', 'abrir mercadinho', 'abrir drogaria', 'abrir ótica', 'abrir cemitério', 'abrir quartel', 'abrir universidade', 'abrir creche',
    'abrir fórum', 'abrir prefeitura', 'abrir ginásio', 'abrir quadra poliesportiva', 'abrir clube', 'abrir spa', 'abrir sauna', 'abrir boate',
    'abrir bar', 'abrir pub', 'abrir confeitaria', 'abrir hamburgueria', 'abrir pizzaria', 'abrir churrascaria', 'abrir sushi bar', 'abrir food truck',
    'abrir camping', 'abrir pousada', 'abrir resort', 'abrir teatro', 'abrir ópera', 'abrir galeria de arte', 'abrir livraria', 'abrir papelaria',
    'abrir loja de roupas', 'abrir loja de brinquedos', 'abrir loja de eletrônicos', 'abrir concessionária', 'abrir borracharia', 'abrir autoescola', 'abrir academia de luta', 'abrir piscina pública',
    'abrir quadra de tênis', 'abrir campo de golfe', 'abrir pista de skate', 'abrir pista de atletismo', 'abrir arena', 'abrir castelo', 'abrir palácio', 'abrir catedral',
    'abrir templo', 'abrir torre', 'abrir farol', 'abrir cais', 'abrir marina', 'abrir mina', 'abrir fazenda', 'abrir sítio',
    'abrir vinícola', 'abrir cervejaria', 'abrir fábrica', 'abrir usina', 'abrir base militar', 'abrir estação espacial', 'abrir laboratório', 'abrir escritório',
    'abrir coworking', 'abrir call center', 'abrir estúdio de gravação', 'abrir estúdio de tatuagem', 'abrir barbearia', 'abrir clínica veterinária', 'abrir canil', 'abrir abrigo de animais',
    'abrir reserva florestal', 'abrir parque nacional', 'abrir trilha', 'abrir mirante', 'abrir praça de alimentação', 'abrir feira de artesanato', 'abrir mercado municipal', 'abrir feira de rua',
    'abrir antiquário', 'abrir brechó', 'abrir sebo', 'abrir bazar', 'abrir leilão', 'inaugurar cinema', 'inaugurar dentista', 'inaugurar aeroporto',
    'inaugurar praia', 'inaugurar academia', 'inaugurar supermercado', 'inaugurar hospital', 'inaugurar escola', 'inaugurar estádio', 'inaugurar shopping', 'inaugurar zoológico',
    'inaugurar igreja', 'inaugurar restaurante', 'inaugurar padaria', 'inaugurar salão de beleza', 'inaugurar posto de gasolina', 'inaugurar biblioteca', 'inaugurar museu', 'inaugurar parque',
    'inaugurar farmácia', 'inaugurar banco', 'inaugurar correio', 'inaugurar delegacia', 'inaugurar feira', 'inaugurar açougue', 'inaugurar oficina mecânica', 'inaugurar lavanderia',
    'inaugurar pet shop', 'inaugurar floricultura', 'inaugurar sorveteria', 'inaugurar lanchonete', 'inaugurar consultório', 'inaugurar cartório', 'inaugurar rodoviária', 'inaugurar metrô',
    'inaugurar praça', 'inaugurar circo', 'inaugurar parque de diversões', 'inaugurar aquário', 'inaugurar planetário', 'inaugurar hotel', 'inaugurar motel', 'inaugurar drive-thru',
    'inaugurar feira livre', 'inaugurar mercadinho', 'inaugurar drogaria', 'inaugurar ótica', 'inaugurar cemitério', 'inaugurar quartel', 'inaugurar universidade', 'inaugurar creche',
    'inaugurar fórum', 'inaugurar prefeitura', 'inaugurar ginásio', 'inaugurar quadra poliesportiva', 'inaugurar clube', 'inaugurar spa', 'inaugurar sauna', 'inaugurar boate',
    'inaugurar bar', 'inaugurar pub', 'inaugurar confeitaria', 'inaugurar hamburgueria', 'inaugurar pizzaria', 'inaugurar churrascaria', 'inaugurar sushi bar', 'inaugurar food truck',
    'inaugurar camping', 'inaugurar pousada', 'inaugurar resort', 'inaugurar teatro', 'inaugurar ópera', 'inaugurar galeria de arte', 'inaugurar livraria', 'inaugurar papelaria',
    'inaugurar loja de roupas', 'inaugurar loja de brinquedos', 'inaugurar loja de eletrônicos', 'inaugurar concessionária', 'inaugurar borracharia', 'inaugurar autoescola', 'inaugurar academia de luta', 'inaugurar piscina pública',
    'inaugurar quadra de tênis', 'inaugurar campo de golfe', 'inaugurar pista de skate', 'inaugurar pista de atletismo', 'inaugurar arena', 'inaugurar castelo', 'inaugurar palácio', 'inaugurar catedral',
    'inaugurar templo', 'inaugurar torre', 'inaugurar farol', 'inaugurar cais', 'inaugurar marina', 'inaugurar mina', 'inaugurar fazenda', 'inaugurar sítio',
    'inaugurar vinícola', 'inaugurar cervejaria', 'inaugurar fábrica', 'inaugurar usina', 'inaugurar base militar', 'inaugurar estação espacial', 'inaugurar laboratório', 'inaugurar escritório',
    'inaugurar coworking', 'inaugurar call center', 'inaugurar estúdio de gravação', 'inaugurar estúdio de tatuagem', 'inaugurar barbearia', 'inaugurar clínica veterinária', 'inaugurar canil', 'inaugurar abrigo de animais',
    'inaugurar reserva florestal', 'inaugurar parque nacional', 'inaugurar trilha', 'inaugurar mirante', 'inaugurar praça de alimentação', 'inaugurar feira de artesanato', 'inaugurar mercado municipal', 'inaugurar feira de rua',
    'inaugurar antiquário', 'inaugurar brechó', 'inaugurar sebo', 'inaugurar bazar', 'inaugurar leilão', 'reformar cinema', 'reformar dentista', 'reformar aeroporto',
    'reformar praia', 'reformar academia', 'reformar supermercado', 'reformar hospital', 'reformar escola', 'reformar estádio', 'reformar shopping', 'reformar zoológico',
    'reformar igreja', 'reformar restaurante', 'reformar padaria', 'reformar salão de beleza', 'reformar posto de gasolina', 'reformar biblioteca', 'reformar museu', 'reformar parque',
    'reformar farmácia', 'reformar banco', 'reformar correio', 'reformar delegacia', 'reformar feira', 'reformar açougue', 'reformar oficina mecânica', 'reformar lavanderia',
    'reformar pet shop', 'reformar floricultura', 'reformar sorveteria', 'reformar lanchonete', 'reformar consultório', 'reformar cartório', 'reformar rodoviária', 'reformar metrô',
    'reformar praça', 'reformar circo', 'reformar parque de diversões', 'reformar aquário', 'reformar planetário', 'reformar hotel', 'reformar motel', 'reformar drive-thru',
    'reformar feira livre', 'reformar mercadinho', 'reformar drogaria', 'reformar ótica', 'reformar cemitério', 'reformar quartel', 'reformar universidade', 'reformar creche',
    'reformar fórum', 'reformar prefeitura', 'reformar ginásio', 'reformar quadra poliesportiva', 'reformar clube', 'reformar spa', 'reformar sauna', 'reformar boate',
    'reformar bar', 'reformar pub', 'reformar confeitaria', 'reformar hamburgueria', 'reformar pizzaria', 'reformar churrascaria', 'reformar sushi bar', 'reformar food truck',
    'reformar camping', 'reformar pousada', 'reformar resort', 'reformar teatro', 'reformar ópera', 'reformar galeria de arte', 'reformar livraria', 'reformar papelaria',
    'reformar loja de roupas', 'reformar loja de brinquedos', 'reformar loja de eletrônicos', 'reformar concessionária', 'reformar borracharia', 'reformar autoescola', 'reformar academia de luta', 'reformar piscina pública',
    'reformar quadra de tênis', 'reformar campo de golfe', 'reformar pista de skate', 'reformar pista de atletismo', 'reformar arena', 'reformar castelo', 'reformar palácio', 'reformar catedral',
    'reformar templo', 'reformar torre', 'reformar farol', 'reformar cais', 'reformar marina', 'reformar mina', 'reformar fazenda', 'reformar sítio',
    'reformar vinícola', 'reformar cervejaria', 'reformar fábrica', 'reformar usina', 'reformar base militar', 'reformar estação espacial', 'reformar laboratório', 'reformar escritório',
    'reformar coworking', 'reformar call center', 'reformar estúdio de gravação', 'reformar estúdio de tatuagem', 'reformar barbearia', 'reformar clínica veterinária', 'reformar canil', 'reformar abrigo de animais',
    'reformar reserva florestal', 'reformar parque nacional', 'reformar trilha', 'reformar mirante', 'reformar praça de alimentação', 'reformar feira de artesanato', 'reformar mercado municipal', 'reformar feira de rua',
    'reformar antiquário', 'reformar brechó', 'reformar sebo', 'reformar bazar', 'reformar leilão', 'construir cinema', 'construir dentista', 'construir aeroporto',
  ],
  4: [
    'ciúme', 'fila do banco', 'madrugada', 'saudade', 'preguiça', 'vergonha', 'medo do escuro', 'dor de dente',
    'insônia', 'engarrafamento', 'virada de ano', 'aniversário surpresa', 'dia de faxina', 'prova final', 'primeiro encontro', 'gol contra',
    'briga de trânsito', 'cabelo bagunçado', 'fome', 'sede', 'calor', 'frio', 'tédio', 'sono',
    'fofoca', 'susto', 'timidez', 'pânico', 'gripe', 'tontura', 'mudança de casa', 'fim de semana',
    'segunda-feira', 'hora do almoço', 'dia de pagamento', 'chuva de granizo', 'apagão', 'dia dos namorados', 'carnaval', 'copa do mundo',
    'entrevista de emprego', 'reunião chata', 'trote de faculdade', 'noite de insônia', 'desfile de moda', 'aula de yoga', 'consulta médica', 'assalto',
    'lua de mel', 'despedida', 'nostalgia', 'euforia', 'melancolia', 'alívio', 'orgulho', 'raiva',
    'inveja', 'gratidão', 'ansiedade', 'coragem', 'solidão', 'esperança', 'surpresa', 'confusão',
    'curiosidade', 'arrependimento', 'empolgação', 'frustração', 'exaustão', 'paciência', 'impaciência', 'gula',
    'preguiça matinal', 'azia', 'fila do padaria', 'fila do caixa', 'fila do trânsito', 'fila do prova', 'fila do chuva', 'fila do escuro',
    'fila do altura', 'fila do palco', 'fila do agulha', 'fila do faxina', 'fila do mudança', 'fila do verão', 'fila do inverno', 'fila do natal',
    'fila do ano-novo', 'fila do carnaval', 'fila do páscoa', 'fila do segunda-feira', 'fila do sexta-feira', 'fila do almoço', 'fila do jantar', 'fila do sono',
    'fila do trabalho', 'fila do viagem', 'fila do namoro', 'fila do casamento', 'fila do formatura', 'fila do entrevista', 'fila do reunião', 'fila do aniversário',
    'fila do despedida', 'fila do chegada', 'fila do partida', 'fila do exame', 'fila do consulta', 'fila do cirurgia', 'fila do gripe', 'fila do alergia',
    'fila do dor de cabeça', 'fila da banco', 'fila da padaria', 'fila da caixa', 'fila da trânsito', 'fila da prova', 'fila da chuva', 'fila da escuro',
    'fila da altura', 'fila da palco', 'fila da agulha', 'fila da faxina', 'fila da mudança', 'fila da verão', 'fila da inverno', 'fila da natal',
    'fila da ano-novo', 'fila da carnaval', 'fila da páscoa', 'fila da segunda-feira', 'fila da sexta-feira', 'fila da almoço', 'fila da jantar', 'fila da sono',
    'fila da trabalho', 'fila da viagem', 'fila da namoro', 'fila da casamento', 'fila da formatura', 'fila da entrevista', 'fila da reunião', 'fila da aniversário',
    'fila da despedida', 'fila da chegada', 'fila da partida', 'fila da exame', 'fila da consulta', 'fila da cirurgia', 'fila da gripe', 'fila da alergia',
    'fila da dor de cabeça', 'dia de banco', 'dia de padaria', 'dia de caixa', 'dia de trânsito', 'dia de prova', 'dia de chuva', 'dia de escuro',
    'dia de altura', 'dia de palco', 'dia de agulha', 'dia de mudança', 'dia de verão', 'dia de inverno', 'dia de natal', 'dia de ano-novo',
    'dia de carnaval', 'dia de páscoa', 'dia de segunda-feira', 'dia de sexta-feira', 'dia de almoço', 'dia de jantar', 'dia de sono', 'dia de trabalho',
    'dia de viagem', 'dia de namoro', 'dia de casamento', 'dia de formatura', 'dia de entrevista', 'dia de reunião', 'dia de aniversário', 'dia de despedida',
    'dia de chegada', 'dia de partida', 'dia de exame', 'dia de consulta', 'dia de cirurgia', 'dia de gripe', 'dia de alergia', 'dia de dor de cabeça',
    'dia da banco', 'dia da padaria', 'dia da caixa', 'dia da trânsito', 'dia da prova', 'dia da chuva', 'dia da escuro', 'dia da altura',
    'dia da palco', 'dia da agulha', 'dia da faxina', 'dia da mudança', 'dia da verão', 'dia da inverno', 'dia da natal', 'dia da ano-novo',
    'dia da carnaval', 'dia da páscoa', 'dia da segunda-feira', 'dia da sexta-feira', 'dia da almoço', 'dia da jantar', 'dia da sono', 'dia da trabalho',
    'dia da viagem', 'dia da namoro', 'dia da casamento', 'dia da formatura', 'dia da entrevista', 'dia da reunião', 'dia da aniversário', 'dia da despedida',
    'dia da chegada', 'dia da partida', 'dia da exame', 'dia da consulta', 'dia da cirurgia', 'dia da gripe', 'dia da alergia', 'dia da dor de cabeça',
    'hora do banco', 'hora do padaria', 'hora do caixa', 'hora do trânsito', 'hora do prova', 'hora do chuva', 'hora do escuro', 'hora do altura',
    'hora do palco', 'hora do agulha', 'hora do faxina', 'hora do mudança', 'hora do verão', 'hora do inverno', 'hora do natal', 'hora do ano-novo',
    'hora do carnaval', 'hora do páscoa', 'hora do segunda-feira', 'hora do sexta-feira', 'hora do jantar', 'hora do sono', 'hora do trabalho', 'hora do viagem',
    'hora do namoro', 'hora do casamento', 'hora do formatura', 'hora do entrevista', 'hora do reunião', 'hora do aniversário', 'hora do despedida', 'hora do chegada',
    'hora do partida', 'hora do exame', 'hora do consulta', 'hora do cirurgia', 'hora do gripe', 'hora do alergia', 'hora do dor de cabeça', 'hora da banco',
    'hora da padaria', 'hora da caixa', 'hora da trânsito', 'hora da prova', 'hora da chuva', 'hora da escuro', 'hora da altura', 'hora da palco',
    'hora da agulha', 'hora da faxina', 'hora da mudança', 'hora da verão', 'hora da inverno', 'hora da natal', 'hora da ano-novo', 'hora da carnaval',
    'hora da páscoa', 'hora da segunda-feira', 'hora da sexta-feira', 'hora da almoço', 'hora da jantar', 'hora da sono', 'hora da trabalho', 'hora da viagem',
    'hora da namoro', 'hora da casamento', 'hora da formatura', 'hora da entrevista', 'hora da reunião', 'hora da aniversário', 'hora da despedida', 'hora da chegada',
    'hora da partida', 'hora da exame', 'hora da consulta', 'hora da cirurgia', 'hora da gripe', 'hora da alergia', 'hora da dor de cabeça', 'medo de banco',
    'medo de padaria', 'medo de caixa', 'medo de trânsito', 'medo de prova', 'medo de chuva', 'medo de escuro', 'medo de altura', 'medo de palco',
    'medo de agulha', 'medo de faxina', 'medo de mudança', 'medo de verão', 'medo de inverno', 'medo de natal', 'medo de ano-novo', 'medo de carnaval',
    'medo de páscoa', 'medo de segunda-feira', 'medo de sexta-feira', 'medo de almoço', 'medo de jantar', 'medo de sono', 'medo de trabalho', 'medo de viagem',
    'medo de namoro', 'medo de casamento', 'medo de formatura', 'medo de entrevista', 'medo de reunião', 'medo de aniversário', 'medo de despedida', 'medo de chegada',
    'medo de partida', 'medo de exame', 'medo de consulta', 'medo de cirurgia', 'medo de gripe', 'medo de alergia', 'medo de dor de cabeça', 'medo do banco',
    'medo do padaria', 'medo do caixa', 'medo do trânsito', 'medo do prova', 'medo do chuva', 'medo do altura', 'medo do palco', 'medo do agulha',
    'medo do faxina', 'medo do mudança', 'medo do verão', 'medo do inverno', 'medo do natal', 'medo do ano-novo', 'medo do carnaval', 'medo do páscoa',
    'medo do segunda-feira', 'medo do sexta-feira', 'medo do almoço', 'medo do jantar', 'medo do sono', 'medo do trabalho', 'medo do viagem', 'medo do namoro',
    'medo do casamento', 'medo do formatura', 'medo do entrevista', 'medo do reunião', 'medo do aniversário', 'medo do despedida', 'medo do chegada', 'medo do partida',
    'medo do exame', 'medo do consulta', 'medo do cirurgia', 'medo do gripe', 'medo do alergia', 'medo do dor de cabeça', 'cheiro de banco', 'cheiro de padaria',
    'cheiro de caixa', 'cheiro de trânsito', 'cheiro de prova', 'cheiro de chuva', 'cheiro de escuro', 'cheiro de altura', 'cheiro de palco', 'cheiro de agulha',
    'cheiro de faxina', 'cheiro de mudança', 'cheiro de verão', 'cheiro de inverno', 'cheiro de natal', 'cheiro de ano-novo', 'cheiro de carnaval', 'cheiro de páscoa',
    'cheiro de segunda-feira', 'cheiro de sexta-feira', 'cheiro de almoço', 'cheiro de jantar', 'cheiro de sono', 'cheiro de trabalho', 'cheiro de viagem', 'cheiro de namoro',
    'cheiro de casamento', 'cheiro de formatura', 'cheiro de entrevista', 'cheiro de reunião', 'cheiro de aniversário', 'cheiro de despedida', 'cheiro de chegada', 'cheiro de partida',
    'cheiro de exame', 'cheiro de consulta', 'cheiro de cirurgia', 'cheiro de gripe', 'cheiro de alergia', 'cheiro de dor de cabeça', 'época de banco', 'época de padaria',
    'época de caixa', 'época de trânsito', 'época de prova', 'época de chuva', 'época de escuro', 'época de altura', 'época de palco', 'época de agulha',
    'época de faxina', 'época de mudança', 'época de verão', 'época de inverno', 'época de natal', 'época de ano-novo', 'época de carnaval', 'época de páscoa',
    'época de segunda-feira', 'época de sexta-feira', 'época de almoço', 'época de jantar', 'época de sono', 'época de trabalho', 'época de viagem', 'época de namoro',
    'época de casamento', 'época de formatura', 'época de entrevista', 'época de reunião', 'época de aniversário', 'época de despedida', 'época de chegada', 'época de partida',
    'época de exame', 'época de consulta', 'época de cirurgia', 'época de gripe', 'época de alergia', 'época de dor de cabeça', 'noite de banco', 'noite de padaria',
    'noite de caixa', 'noite de trânsito', 'noite de prova', 'noite de chuva', 'noite de escuro', 'noite de altura', 'noite de palco', 'noite de agulha',
    'noite de faxina', 'noite de mudança', 'noite de verão', 'noite de inverno', 'noite de natal', 'noite de ano-novo', 'noite de carnaval', 'noite de páscoa',
    'noite de segunda-feira', 'noite de sexta-feira', 'noite de almoço', 'noite de jantar', 'noite de sono', 'noite de trabalho', 'noite de viagem', 'noite de namoro',
    'noite de casamento', 'noite de formatura', 'noite de entrevista', 'noite de reunião', 'noite de aniversário', 'noite de despedida', 'noite de chegada', 'noite de partida',
    'noite de exame', 'noite de consulta', 'noite de cirurgia', 'noite de gripe', 'noite de alergia', 'noite de dor de cabeça', 'manhã de banco', 'manhã de padaria',
    'manhã de caixa', 'manhã de trânsito', 'manhã de prova', 'manhã de chuva', 'manhã de escuro', 'manhã de altura', 'manhã de palco', 'manhã de agulha',
    'manhã de faxina', 'manhã de mudança', 'manhã de verão', 'manhã de inverno', 'manhã de natal', 'manhã de ano-novo', 'manhã de carnaval', 'manhã de páscoa',
    'manhã de segunda-feira', 'manhã de sexta-feira', 'manhã de almoço', 'manhã de jantar', 'manhã de sono', 'manhã de trabalho', 'manhã de viagem', 'manhã de namoro',
    'manhã de casamento', 'manhã de formatura', 'manhã de entrevista', 'manhã de reunião', 'manhã de aniversário', 'manhã de despedida', 'manhã de chegada', 'manhã de partida',
    'manhã de exame', 'manhã de consulta', 'manhã de cirurgia', 'manhã de gripe', 'manhã de alergia', 'manhã de dor de cabeça', 'tarde de banco', 'tarde de padaria',
    'tarde de caixa', 'tarde de trânsito', 'tarde de prova', 'tarde de chuva', 'tarde de escuro', 'tarde de altura', 'tarde de palco', 'tarde de agulha',
    'tarde de faxina', 'tarde de mudança', 'tarde de verão', 'tarde de inverno', 'tarde de natal', 'tarde de ano-novo', 'tarde de carnaval', 'tarde de páscoa',
    'tarde de segunda-feira', 'tarde de sexta-feira', 'tarde de almoço', 'tarde de jantar', 'tarde de sono', 'tarde de trabalho', 'tarde de viagem', 'tarde de namoro',
    'tarde de casamento', 'tarde de formatura', 'tarde de entrevista', 'tarde de reunião', 'tarde de aniversário', 'tarde de despedida', 'tarde de chegada', 'tarde de partida',
    'tarde de exame', 'tarde de consulta', 'tarde de cirurgia', 'tarde de gripe', 'tarde de alergia', 'tarde de dor de cabeça', 'véspera de banco', 'véspera de padaria',
    'véspera de caixa', 'véspera de trânsito', 'véspera de prova', 'véspera de chuva', 'véspera de escuro', 'véspera de altura', 'véspera de palco', 'véspera de agulha',
    'véspera de faxina', 'véspera de mudança', 'véspera de verão', 'véspera de inverno', 'véspera de natal', 'véspera de ano-novo', 'véspera de carnaval', 'véspera de páscoa',
    'véspera de segunda-feira', 'véspera de sexta-feira', 'véspera de almoço', 'véspera de jantar', 'véspera de sono', 'véspera de trabalho', 'véspera de viagem', 'véspera de namoro',
    'véspera de casamento', 'véspera de formatura', 'véspera de entrevista', 'véspera de reunião', 'véspera de aniversário', 'véspera de despedida', 'véspera de chegada', 'véspera de partida',
    'véspera de exame', 'véspera de consulta', 'véspera de cirurgia', 'véspera de gripe', 'véspera de alergia', 'véspera de dor de cabeça', 'ressaca de banco', 'ressaca de padaria',
    'ressaca de caixa', 'ressaca de trânsito', 'ressaca de prova', 'ressaca de chuva', 'ressaca de escuro', 'ressaca de altura', 'ressaca de palco', 'ressaca de agulha',
    'ressaca de faxina', 'ressaca de mudança', 'ressaca de verão', 'ressaca de inverno', 'ressaca de natal', 'ressaca de ano-novo', 'ressaca de carnaval', 'ressaca de páscoa',
    'ressaca de segunda-feira', 'ressaca de sexta-feira', 'ressaca de almoço', 'ressaca de jantar', 'ressaca de sono', 'ressaca de trabalho', 'ressaca de viagem', 'ressaca de namoro',
    'ressaca de casamento', 'ressaca de formatura', 'ressaca de entrevista', 'ressaca de reunião', 'ressaca de aniversário', 'ressaca de despedida', 'ressaca de chegada', 'ressaca de partida',
    'ressaca de exame', 'ressaca de consulta', 'ressaca de cirurgia', 'ressaca de gripe', 'ressaca de alergia', 'ressaca de dor de cabeça', 'crise de banco', 'crise de padaria',
    'crise de caixa', 'crise de trânsito', 'crise de prova', 'crise de chuva', 'crise de escuro', 'crise de altura', 'crise de palco', 'crise de agulha',
    'crise de faxina', 'crise de mudança', 'crise de verão', 'crise de inverno', 'crise de natal', 'crise de ano-novo', 'crise de carnaval', 'crise de páscoa',
    'crise de segunda-feira', 'crise de sexta-feira', 'crise de almoço', 'crise de jantar', 'crise de sono', 'crise de trabalho', 'crise de viagem', 'crise de namoro',
    'crise de casamento', 'crise de formatura', 'crise de entrevista', 'crise de reunião', 'crise de aniversário', 'crise de despedida', 'crise de chegada', 'crise de partida',
    'crise de exame', 'crise de consulta', 'crise de cirurgia', 'crise de gripe', 'crise de alergia', 'crise de dor de cabeça', 'ataque de banco', 'ataque de padaria',
    'ataque de caixa', 'ataque de trânsito', 'ataque de prova', 'ataque de chuva', 'ataque de escuro', 'ataque de altura', 'ataque de palco', 'ataque de agulha',
    'ataque de faxina', 'ataque de mudança', 'ataque de verão', 'ataque de inverno', 'ataque de natal', 'ataque de ano-novo', 'ataque de carnaval', 'ataque de páscoa',
    'ataque de segunda-feira', 'ataque de sexta-feira', 'ataque de almoço', 'ataque de jantar', 'ataque de sono', 'ataque de trabalho', 'ataque de viagem', 'ataque de namoro',
    'ataque de casamento', 'ataque de formatura', 'ataque de entrevista', 'ataque de reunião', 'ataque de aniversário', 'ataque de despedida', 'ataque de chegada', 'ataque de partida',
    'ataque de exame', 'ataque de consulta', 'ataque de cirurgia', 'ataque de gripe', 'ataque de alergia', 'ataque de dor de cabeça', 'excesso de banco', 'excesso de padaria',
    'excesso de caixa', 'excesso de trânsito', 'excesso de prova', 'excesso de chuva', 'excesso de escuro', 'excesso de altura', 'excesso de palco', 'excesso de agulha',
    'excesso de faxina', 'excesso de mudança', 'excesso de verão', 'excesso de inverno', 'excesso de natal', 'excesso de ano-novo', 'excesso de carnaval', 'excesso de páscoa',
    'excesso de segunda-feira', 'excesso de sexta-feira', 'excesso de almoço', 'excesso de jantar', 'excesso de sono', 'excesso de trabalho', 'excesso de viagem', 'excesso de namoro',
    'excesso de casamento', 'excesso de formatura', 'excesso de entrevista', 'excesso de reunião', 'excesso de aniversário', 'excesso de despedida', 'excesso de chegada', 'excesso de partida',
    'excesso de exame', 'excesso de consulta', 'excesso de cirurgia', 'excesso de gripe', 'excesso de alergia', 'excesso de dor de cabeça', 'falta de banco', 'falta de padaria',
    'falta de caixa', 'falta de trânsito', 'falta de prova', 'falta de chuva', 'falta de escuro', 'falta de altura', 'falta de palco', 'falta de agulha',
    'falta de faxina', 'falta de mudança', 'falta de verão', 'falta de inverno', 'falta de natal', 'falta de ano-novo', 'falta de carnaval', 'falta de páscoa',
    'falta de segunda-feira', 'falta de sexta-feira', 'falta de almoço', 'falta de jantar', 'falta de sono', 'falta de trabalho', 'falta de viagem', 'falta de namoro',
    'falta de casamento', 'falta de formatura', 'falta de entrevista', 'falta de reunião', 'falta de aniversário', 'falta de despedida', 'falta de chegada', 'falta de partida',
    'falta de exame', 'falta de consulta', 'falta de cirurgia', 'falta de gripe', 'falta de alergia', 'falta de dor de cabeça', 'demora no banco', 'demora no padaria',
    'demora no caixa', 'demora no trânsito', 'demora no prova', 'demora no chuva', 'demora no escuro', 'demora no altura', 'demora no palco', 'demora no agulha',
    'demora no faxina', 'demora no mudança', 'demora no verão', 'demora no inverno', 'demora no natal', 'demora no ano-novo', 'demora no carnaval', 'demora no páscoa',
    'demora no segunda-feira', 'demora no sexta-feira', 'demora no almoço', 'demora no jantar', 'demora no sono', 'demora no trabalho', 'demora no viagem', 'demora no namoro',
    'demora no casamento', 'demora no formatura', 'demora no entrevista', 'demora no reunião', 'demora no aniversário', 'demora no despedida', 'demora no chegada', 'demora no partida',
    'demora no exame', 'demora no consulta', 'demora no cirurgia', 'demora no gripe', 'demora no alergia', 'demora no dor de cabeça', 'clima de banco', 'clima de padaria',
    'clima de caixa', 'clima de trânsito', 'clima de prova', 'clima de chuva', 'clima de escuro', 'clima de altura', 'clima de palco', 'clima de agulha',
    'clima de faxina', 'clima de mudança', 'clima de verão', 'clima de inverno', 'clima de natal', 'clima de ano-novo', 'clima de carnaval', 'clima de páscoa',
    'clima de segunda-feira', 'clima de sexta-feira', 'clima de almoço', 'clima de jantar', 'clima de sono', 'clima de trabalho', 'clima de viagem', 'clima de namoro',
    'clima de casamento', 'clima de formatura', 'clima de entrevista', 'clima de reunião', 'clima de aniversário', 'clima de despedida', 'clima de chegada', 'clima de partida',
    'clima de exame', 'clima de consulta', 'clima de cirurgia', 'clima de gripe', 'clima de alergia', 'clima de dor de cabeça', 'lembrança de banco', 'lembrança de padaria',
    'lembrança de caixa', 'lembrança de trânsito', 'lembrança de prova', 'lembrança de chuva', 'lembrança de escuro', 'lembrança de altura', 'lembrança de palco', 'lembrança de agulha',
    'lembrança de faxina', 'lembrança de mudança', 'lembrança de verão', 'lembrança de inverno', 'lembrança de natal', 'lembrança de ano-novo', 'lembrança de carnaval', 'lembrança de páscoa',
    'lembrança de segunda-feira', 'lembrança de sexta-feira', 'lembrança de almoço', 'lembrança de jantar', 'lembrança de sono', 'lembrança de trabalho', 'lembrança de viagem', 'lembrança de namoro',
    'lembrança de casamento', 'lembrança de formatura', 'lembrança de entrevista', 'lembrança de reunião', 'lembrança de aniversário', 'lembrança de despedida', 'lembrança de chegada', 'lembrança de partida',
    'lembrança de exame', 'lembrança de consulta', 'lembrança de cirurgia', 'lembrança de gripe', 'lembrança de alergia', 'lembrança de dor de cabeça', 'sensação de banco', 'sensação de padaria',
    'sensação de caixa', 'sensação de trânsito', 'sensação de prova', 'sensação de chuva', 'sensação de escuro', 'sensação de altura', 'sensação de palco', 'sensação de agulha',
    'sensação de faxina', 'sensação de mudança', 'sensação de verão', 'sensação de inverno', 'sensação de natal', 'sensação de ano-novo', 'sensação de carnaval', 'sensação de páscoa',
    'sensação de segunda-feira', 'sensação de sexta-feira', 'sensação de almoço', 'sensação de jantar', 'sensação de sono', 'sensação de trabalho', 'sensação de viagem', 'sensação de namoro',
    'sensação de casamento', 'sensação de formatura', 'sensação de entrevista', 'sensação de reunião', 'sensação de aniversário', 'sensação de despedida', 'sensação de chegada', 'sensação de partida',
    'sensação de exame', 'sensação de consulta', 'sensação de cirurgia', 'sensação de gripe', 'sensação de alergia', 'sensação de dor de cabeça', 'barulho de banco', 'barulho de padaria',
    'barulho de caixa', 'barulho de trânsito', 'barulho de prova', 'barulho de chuva', 'barulho de escuro', 'barulho de altura', 'barulho de palco', 'barulho de agulha',
  ],
  5: [
    'pagar boleto atrasado', 'perder o ônibus', 'ressaca de segunda', 'esquecer a senha', 'pisar em lego', 'celular sem bateria', 'pneu furado', 'wi-fi caindo',
    'acordar atrasado', 'roubar a coberta', 'cair da cadeira', 'sogra chegando', 'piscina fria', 'fila do INSS', 'dieta de segunda', 'esquecer o nome',
    'choque no chuveiro', 'cachorro comeu lição', 'chuva sem guarda-chuva', 'chave no carro', 'dormir no cinema', 'cantar no chuveiro', 'perder o voo', 'fila do banheiro',
    'ligar pro ex', 'roubar a sobremesa', 'esquecer o aniversário', 'sapato apertado', 'pisar em cocô', 'cair no golpe', 'carro sem gasolina', 'mosquito na orelha',
    'música na cabeça', 'travar na apresentação', 'errar a mensagem', 'dinheiro no bolso', 'comer pimenta forte', 'derrubar o celular', 'espirrar de máscara', 'gato na madrugada',
    'preso no elevador', 'engolir chiclete', 'engasgar com água', 'bronca do chefe', 'perder a carteira', 'pegar sol demais', 'escada rolante parada', 'cortar cebola',
    'apertar botão errado', 'fantasma na casa', 'perder wi-fi', 'perder celular', 'perder computador', 'perder senha', 'perder carregador', 'perder fone de ouvido',
    'perder bateria', 'perder aplicativo', 'perder mensagem', 'perder foto', 'perder vídeo', 'perder arquivo', 'perder documento', 'perder e-mail',
    'perder reunião online', 'perder microfone', 'perder câmera', 'perder projetor', 'perder cabo', 'perder tomada', 'perder roteador', 'perder impressora',
    'perder tablet', 'perder smartwatch', 'perder fatura', 'perder boleto', 'perder conta de luz', 'perder senha do wi-fi', 'perder cartão de crédito', 'perder notebook',
    'perder monitor', 'perder teclado', 'perder mouse', 'perder pen-drive', 'perder fatura do cartão', 'perder assinatura', 'perder notificação', 'perder atualização',
    'perder backup', 'perder extrato bancário', 'perder cupom de desconto', 'perder código de rastreio', 'perder pedido online', 'perder login', 'perder token', 'perder antivírus',
    'perder plano de dados', 'perder sinal de internet', 'travar em wi-fi', 'travar em celular', 'travar em computador', 'travar em senha', 'travar em carregador', 'travar em fone de ouvido',
    'travar em bateria', 'travar em aplicativo', 'travar em mensagem', 'travar em foto', 'travar em vídeo', 'travar em arquivo', 'travar em documento', 'travar em e-mail',
    'travar em reunião online', 'travar em microfone', 'travar em câmera', 'travar em projetor', 'travar em cabo', 'travar em tomada', 'travar em roteador', 'travar em impressora',
    'travar em tablet', 'travar em smartwatch', 'travar em fatura', 'travar em boleto', 'travar em conta de luz', 'travar em senha do wi-fi', 'travar em cartão de crédito', 'travar em notebook',
    'travar em monitor', 'travar em teclado', 'travar em mouse', 'travar em pen-drive', 'travar em fatura do cartão', 'travar em assinatura', 'travar em notificação', 'travar em atualização',
    'travar em backup', 'travar em extrato bancário', 'travar em cupom de desconto', 'travar em código de rastreio', 'travar em pedido online', 'travar em login', 'travar em token', 'travar em antivírus',
    'travar em plano de dados', 'travar em sinal de internet', 'derrubar wi-fi', 'derrubar celular', 'derrubar computador', 'derrubar senha', 'derrubar carregador', 'derrubar fone de ouvido',
    'derrubar bateria', 'derrubar aplicativo', 'derrubar mensagem', 'derrubar foto', 'derrubar vídeo', 'derrubar arquivo', 'derrubar documento', 'derrubar e-mail',
    'derrubar reunião online', 'derrubar microfone', 'derrubar câmera', 'derrubar projetor', 'derrubar cabo', 'derrubar tomada', 'derrubar roteador', 'derrubar impressora',
    'derrubar tablet', 'derrubar smartwatch', 'derrubar fatura', 'derrubar boleto', 'derrubar conta de luz', 'derrubar senha do wi-fi', 'derrubar cartão de crédito', 'derrubar notebook',
    'derrubar monitor', 'derrubar teclado', 'derrubar mouse', 'derrubar pen-drive', 'derrubar fatura do cartão', 'derrubar assinatura', 'derrubar notificação', 'derrubar atualização',
    'derrubar backup', 'derrubar extrato bancário', 'derrubar cupom de desconto', 'derrubar código de rastreio', 'derrubar pedido online', 'derrubar login', 'derrubar token', 'derrubar antivírus',
    'derrubar plano de dados', 'derrubar sinal de internet', 'quebrar wi-fi', 'quebrar celular', 'quebrar computador', 'quebrar senha', 'quebrar carregador', 'quebrar fone de ouvido',
    'quebrar bateria', 'quebrar aplicativo', 'quebrar mensagem', 'quebrar foto', 'quebrar vídeo', 'quebrar arquivo', 'quebrar documento', 'quebrar e-mail',
    'quebrar reunião online', 'quebrar microfone', 'quebrar câmera', 'quebrar projetor', 'quebrar cabo', 'quebrar tomada', 'quebrar roteador', 'quebrar impressora',
    'quebrar tablet', 'quebrar smartwatch', 'quebrar fatura', 'quebrar boleto', 'quebrar conta de luz', 'quebrar senha do wi-fi', 'quebrar cartão de crédito', 'quebrar notebook',
    'quebrar monitor', 'quebrar teclado', 'quebrar mouse', 'quebrar pen-drive', 'quebrar fatura do cartão', 'quebrar assinatura', 'quebrar notificação', 'quebrar atualização',
    'quebrar backup', 'quebrar extrato bancário', 'quebrar cupom de desconto', 'quebrar código de rastreio', 'quebrar pedido online', 'quebrar login', 'quebrar token', 'quebrar antivírus',
    'quebrar plano de dados', 'quebrar sinal de internet', 'esquecer wi-fi', 'esquecer celular', 'esquecer computador', 'esquecer senha', 'esquecer carregador', 'esquecer fone de ouvido',
    'esquecer bateria', 'esquecer aplicativo', 'esquecer mensagem', 'esquecer foto', 'esquecer vídeo', 'esquecer arquivo', 'esquecer documento', 'esquecer e-mail',
    'esquecer reunião online', 'esquecer microfone', 'esquecer câmera', 'esquecer projetor', 'esquecer cabo', 'esquecer tomada', 'esquecer roteador', 'esquecer impressora',
    'esquecer tablet', 'esquecer smartwatch', 'esquecer fatura', 'esquecer boleto', 'esquecer conta de luz', 'esquecer senha do wi-fi', 'esquecer cartão de crédito', 'esquecer notebook',
    'esquecer monitor', 'esquecer teclado', 'esquecer mouse', 'esquecer pen-drive', 'esquecer fatura do cartão', 'esquecer assinatura', 'esquecer notificação', 'esquecer atualização',
    'esquecer backup', 'esquecer extrato bancário', 'esquecer cupom de desconto', 'esquecer código de rastreio', 'esquecer pedido online', 'esquecer login', 'esquecer token', 'esquecer antivírus',
    'esquecer plano de dados', 'esquecer sinal de internet', 'perder o fio de wi-fi', 'perder o fio de celular', 'perder o fio de computador', 'perder o fio de senha', 'perder o fio de carregador', 'perder o fio de fone de ouvido',
    'perder o fio de bateria', 'perder o fio de aplicativo', 'perder o fio de mensagem', 'perder o fio de foto', 'perder o fio de vídeo', 'perder o fio de arquivo', 'perder o fio de documento', 'perder o fio de e-mail',
    'perder o fio de reunião online', 'perder o fio de microfone', 'perder o fio de câmera', 'perder o fio de projetor', 'perder o fio de cabo', 'perder o fio de tomada', 'perder o fio de roteador', 'perder o fio de impressora',
    'perder o fio de tablet', 'perder o fio de smartwatch', 'perder o fio de fatura', 'perder o fio de boleto', 'perder o fio de conta de luz', 'perder o fio de senha do wi-fi', 'perder o fio de cartão de crédito', 'perder o fio de notebook',
    'perder o fio de monitor', 'perder o fio de teclado', 'perder o fio de mouse', 'perder o fio de pen-drive', 'perder o fio de fatura do cartão', 'perder o fio de assinatura', 'perder o fio de notificação', 'perder o fio de atualização',
    'perder o fio de backup', 'perder o fio de extrato bancário', 'perder o fio de cupom de desconto', 'perder o fio de código de rastreio', 'perder o fio de pedido online', 'perder o fio de login', 'perder o fio de token', 'perder o fio de antivírus',
    'perder o fio de plano de dados', 'perder o fio de sinal de internet', 'perder ônibus', 'perder trem', 'perder metrô', 'perder táxi', 'perder voo', 'perder carro',
    'perder estacionamento', 'perder vaga', 'perder avião', 'perder barco', 'perder balsa', 'perder van escolar', 'perder carona', 'perder aplicativo de transporte',
    'perder pedágio', 'esquecer ônibus', 'esquecer trem', 'esquecer metrô', 'esquecer táxi', 'esquecer voo', 'esquecer carro', 'esquecer estacionamento',
    'esquecer vaga', 'esquecer avião', 'esquecer barco', 'esquecer balsa', 'esquecer van escolar', 'esquecer carona', 'esquecer aplicativo de transporte', 'esquecer pedágio',
    'atrasar para ônibus', 'atrasar para trem', 'atrasar para metrô', 'atrasar para táxi', 'atrasar para voo', 'atrasar para carro', 'atrasar para estacionamento', 'atrasar para vaga',
    'atrasar para avião', 'atrasar para barco', 'atrasar para balsa', 'atrasar para van escolar', 'atrasar para carona', 'atrasar para aplicativo de transporte', 'atrasar para pedágio', 'trancar-se fora de ônibus',
    'trancar-se fora de trem', 'trancar-se fora de metrô', 'trancar-se fora de táxi', 'trancar-se fora de voo', 'trancar-se fora de carro', 'trancar-se fora de estacionamento', 'trancar-se fora de vaga', 'trancar-se fora de avião',
    'trancar-se fora de barco', 'trancar-se fora de balsa', 'trancar-se fora de van escolar', 'trancar-se fora de carona', 'trancar-se fora de aplicativo de transporte', 'trancar-se fora de pedágio', 'perder chave', 'perder carteira',
    'perder cartão', 'perder óculos', 'perder anel', 'perder aliança', 'perder passaporte', 'perder bilhete', 'perder ingresso', 'perder convite',
    'perder guarda-chuva', 'perder mala', 'perder relógio', 'perder pulseira', 'perder brinco', 'perder colar', 'perder chave do carro', 'perder crachá',
    'perder óculos de sol', 'esquecer chave', 'esquecer carteira', 'esquecer cartão', 'esquecer óculos', 'esquecer anel', 'esquecer aliança', 'esquecer passaporte',
    'esquecer bilhete', 'esquecer ingresso', 'esquecer convite', 'esquecer guarda-chuva', 'esquecer mala', 'esquecer relógio', 'esquecer pulseira', 'esquecer brinco',
    'esquecer colar', 'esquecer chave do carro', 'esquecer crachá', 'esquecer óculos de sol', 'quebrar chave', 'quebrar carteira', 'quebrar cartão', 'quebrar óculos',
    'quebrar anel', 'quebrar aliança', 'quebrar passaporte', 'quebrar bilhete', 'quebrar ingresso', 'quebrar convite', 'quebrar guarda-chuva', 'quebrar mala',
    'quebrar relógio', 'quebrar pulseira', 'quebrar brinco', 'quebrar colar', 'quebrar chave do carro', 'quebrar crachá', 'quebrar óculos de sol', 'derrubar chave',
    'derrubar carteira', 'derrubar cartão', 'derrubar óculos', 'derrubar anel', 'derrubar aliança', 'derrubar passaporte', 'derrubar bilhete', 'derrubar ingresso',
    'derrubar convite', 'derrubar guarda-chuva', 'derrubar mala', 'derrubar relógio', 'derrubar pulseira', 'derrubar brinco', 'derrubar colar', 'derrubar chave do carro',
    'derrubar crachá', 'derrubar óculos de sol', 'procurar desesperado por chave', 'procurar desesperado por carteira', 'procurar desesperado por cartão', 'procurar desesperado por óculos', 'procurar desesperado por anel', 'procurar desesperado por aliança',
    'procurar desesperado por passaporte', 'procurar desesperado por bilhete', 'procurar desesperado por ingresso', 'procurar desesperado por convite', 'procurar desesperado por guarda-chuva', 'procurar desesperado por mala', 'procurar desesperado por relógio', 'procurar desesperado por pulseira',
    'procurar desesperado por brinco', 'procurar desesperado por colar', 'procurar desesperado por chave do carro', 'procurar desesperado por crachá', 'procurar desesperado por óculos de sol', 'esquecer nome', 'esquecer apresentação', 'esquecer entrevista',
    'esquecer reunião', 'esquecer encontro', 'esquecer festa', 'esquecer discurso', 'esquecer prova', 'esquecer aula', 'esquecer casamento', 'esquecer formatura',
    'esquecer aniversário', 'esquecer consulta', 'esquecer cirurgia', 'esquecer viagem', 'esquecer chamada de vídeo', 'esquecer live', 'esquecer palestra', 'errar nome',
    'errar apresentação', 'errar entrevista', 'errar reunião', 'errar encontro', 'errar festa', 'errar discurso', 'errar prova', 'errar aula',
    'errar casamento', 'errar formatura', 'errar aniversário', 'errar consulta', 'errar cirurgia', 'errar viagem', 'errar chamada de vídeo', 'errar live',
    'errar palestra', 'atrasar para nome', 'atrasar para apresentação', 'atrasar para entrevista', 'atrasar para reunião', 'atrasar para encontro', 'atrasar para festa', 'atrasar para discurso',
    'atrasar para prova', 'atrasar para aula', 'atrasar para casamento', 'atrasar para formatura', 'atrasar para aniversário', 'atrasar para consulta', 'atrasar para cirurgia', 'atrasar para viagem',
    'atrasar para chamada de vídeo', 'atrasar para live', 'atrasar para palestra', 'travar em nome', 'travar em apresentação', 'travar em entrevista', 'travar em reunião', 'travar em encontro',
    'travar em festa', 'travar em discurso', 'travar em prova', 'travar em aula', 'travar em casamento', 'travar em formatura', 'travar em aniversário', 'travar em consulta',
    'travar em cirurgia', 'travar em viagem', 'travar em chamada de vídeo', 'travar em live', 'travar em palestra', 'cair em nome', 'cair em apresentação', 'cair em entrevista',
    'cair em reunião', 'cair em encontro', 'cair em festa', 'cair em discurso', 'cair em prova', 'cair em aula', 'cair em casamento', 'cair em formatura',
    'cair em aniversário', 'cair em consulta', 'cair em cirurgia', 'cair em viagem', 'cair em chamada de vídeo', 'cair em live', 'cair em palestra', 'engasgar com pimenta',
    'engasgar com café', 'engasgar com sopa', 'engasgar com legume', 'engasgar com bolo', 'engasgar com salgado', 'engasgar com comida', 'engasgar com prato', 'engasgar com copo',
    'engasgar com macarrão', 'engasgar com arroz', 'engasgar com feijão', 'engasgar com molho', 'engasgar com churrasco', 'engasgar com salada', 'engasgar com suco', 'engasgar com vinho',
    'engasgar com leite', 'queimar pimenta', 'queimar café', 'queimar sopa', 'queimar legume', 'queimar bolo', 'queimar salgado', 'queimar comida',
    'queimar prato', 'queimar copo', 'queimar macarrão', 'queimar arroz', 'queimar feijão', 'queimar molho', 'queimar churrasco', 'queimar salada',
    'queimar suco', 'queimar vinho', 'queimar leite', 'derramar pimenta', 'derramar café', 'derramar sopa', 'derramar legume', 'derramar bolo',
    'derramar salgado', 'derramar comida', 'derramar prato', 'derramar copo', 'derramar macarrão', 'derramar arroz', 'derramar feijão', 'derramar molho',
    'derramar churrasco', 'derramar salada', 'derramar suco', 'derramar vinho', 'derramar leite', 'molhar pimenta', 'molhar café', 'molhar sopa',
    'molhar legume', 'molhar bolo', 'molhar salgado', 'molhar comida', 'molhar prato', 'molhar copo', 'molhar macarrão', 'molhar arroz',
    'molhar feijão', 'molhar molho', 'molhar churrasco', 'molhar salada', 'molhar suco', 'molhar vinho', 'molhar leite', 'estragar pimenta',
    'estragar café', 'estragar sopa', 'estragar legume', 'estragar bolo', 'estragar salgado', 'estragar comida', 'estragar prato', 'estragar copo',
    'estragar macarrão', 'estragar arroz', 'estragar feijão', 'estragar molho', 'estragar churrasco', 'estragar salada', 'estragar suco', 'estragar vinho',
    'estragar leite', 'derrubar fralda', 'derrubar mamadeira', 'derrubar chupeta', 'derrubar brinquedo', 'derrubar controle remoto', 'derrubar geladeira', 'derrubar micro-ondas',
    'derrubar liquidificador', 'derrubar aspirador', 'derrubar berço', 'derrubar carrinho de bebê', 'derrubar secadora', 'derrubar ferro de passar', 'derrubar torradeira', 'derrubar cafeteira',
    'derrubar ventilador', 'quebrar fralda', 'quebrar mamadeira', 'quebrar chupeta', 'quebrar brinquedo', 'quebrar controle remoto', 'quebrar geladeira', 'quebrar micro-ondas',
    'quebrar liquidificador', 'quebrar aspirador', 'quebrar berço', 'quebrar carrinho de bebê', 'quebrar secadora', 'quebrar ferro de passar', 'quebrar torradeira', 'quebrar cafeteira',
    'quebrar ventilador', 'molhar fralda', 'molhar mamadeira', 'molhar chupeta', 'molhar brinquedo', 'molhar controle remoto', 'molhar geladeira', 'molhar micro-ondas',
    'molhar liquidificador', 'molhar aspirador', 'molhar berço', 'molhar carrinho de bebê', 'molhar secadora', 'molhar ferro de passar', 'molhar torradeira', 'molhar cafeteira',
    'molhar ventilador', 'sujar fralda', 'sujar mamadeira', 'sujar chupeta', 'sujar brinquedo', 'sujar controle remoto', 'sujar geladeira', 'sujar micro-ondas',
    'sujar liquidificador', 'sujar aspirador', 'sujar berço', 'sujar carrinho de bebê', 'sujar secadora', 'sujar ferro de passar', 'sujar torradeira', 'sujar cafeteira',
    'sujar ventilador', 'perder fralda', 'perder mamadeira', 'perder chupeta', 'perder brinquedo', 'perder controle remoto', 'perder geladeira', 'perder micro-ondas',
    'perder liquidificador', 'perder aspirador', 'perder berço', 'perder carrinho de bebê', 'perder secadora', 'perder ferro de passar', 'perder torradeira', 'perder cafeteira',
    'perder ventilador', 'pisar em sabão', 'pisar em poça', 'pisar em degrau', 'pisar em tapete', 'pisar em gelo', 'pisar em casca de banana', 'pisar em fio solto',
    'pisar em calçada molhada', 'pisar em escada', 'pisar em buraco na rua', 'escorregar em lego', 'escorregar em sabão', 'escorregar em poça', 'escorregar em degrau', 'escorregar em tapete',
    'escorregar em gelo', 'escorregar em casca de banana', 'escorregar em fio solto', 'escorregar em calçada molhada', 'escorregar em escada', 'escorregar em buraco na rua', 'tropeçar em lego', 'tropeçar em sabão',
    'tropeçar em poça', 'tropeçar em degrau', 'tropeçar em tapete', 'tropeçar em gelo', 'tropeçar em casca de banana', 'tropeçar em fio solto', 'tropeçar em calçada molhada', 'tropeçar em escada',
    'tropeçar em buraco na rua', 'cair em lego', 'cair em sabão', 'cair em poça', 'cair em degrau', 'cair em tapete', 'cair em gelo', 'cair em casca de banana',
    'cair em fio solto', 'cair em calçada molhada', 'cair em escada', 'cair em buraco na rua', 'apertar sapato', 'apertar terno', 'apertar vestido', 'apertar salto',
    'apertar unha', 'apertar botão', 'apertar zíper', 'apertar cinto', 'apertar meia', 'apertar luva', 'apertar jaqueta', 'apertar gravata',
    'apertar cachecol', 'rasgar sapato', 'rasgar terno', 'rasgar vestido', 'rasgar salto', 'rasgar unha', 'rasgar botão', 'rasgar zíper',
    'rasgar cinto', 'rasgar meia', 'rasgar luva', 'rasgar jaqueta', 'rasgar gravata', 'rasgar cachecol', 'amassar sapato', 'amassar terno',
    'amassar vestido', 'amassar salto', 'amassar unha', 'amassar botão', 'amassar zíper', 'amassar cinto', 'amassar meia', 'amassar luva',
    'amassar jaqueta', 'amassar gravata', 'amassar cachecol', 'sujar sapato', 'sujar terno', 'sujar vestido', 'sujar salto', 'sujar unha',
    'sujar botão', 'sujar zíper', 'sujar cinto', 'sujar meia', 'sujar luva', 'sujar jaqueta', 'sujar gravata', 'sujar cachecol',
    'perder sapato', 'perder terno', 'perder vestido', 'perder salto', 'perder unha', 'perder botão', 'perder zíper', 'perder cinto',
    'perder meia', 'perder luva', 'perder jaqueta', 'perder gravata', 'perder cachecol', 'perder relatório', 'perder planilha', 'perder apresentação',
    'perder reunião', 'perder prazo', 'perder e-mail importante', 'perder senha do sistema', 'perder contrato', 'esquecer relatório', 'esquecer planilha', 'esquecer prazo',
    'esquecer e-mail importante', 'esquecer senha do sistema', 'esquecer contrato', 'derrubar relatório', 'derrubar planilha', 'derrubar apresentação', 'derrubar reunião', 'derrubar prazo',
    'derrubar e-mail importante', 'derrubar senha do sistema', 'derrubar contrato', 'errar relatório', 'errar planilha', 'errar prazo', 'errar e-mail importante', 'errar crachá',
    'errar senha do sistema', 'errar arquivo', 'errar contrato', 'atrasar para relatório', 'atrasar para planilha', 'atrasar para prazo', 'atrasar para e-mail importante', 'atrasar para crachá',
    'atrasar para senha do sistema', 'atrasar para arquivo', 'atrasar para contrato', 'perder visto', 'perder passagem', 'perder reserva de hotel', 'perder protetor solar', 'perder câmera de viagem',
    'esquecer visto', 'esquecer passagem', 'esquecer reserva de hotel', 'esquecer protetor solar', 'esquecer câmera de viagem', 'furar passaporte', 'furar visto', 'furar mala',
    'furar passagem', 'furar reserva de hotel', 'furar protetor solar', 'furar câmera de viagem', 'estragar passaporte', 'estragar visto', 'estragar mala', 'estragar passagem',
    'estragar reserva de hotel', 'estragar protetor solar', 'estragar câmera de viagem', 'entupir pia', 'entupir vaso sanitário', 'entupir cano', 'entupir torneira', 'entupir chuveiro',
    'entupir tomada', 'entupir disjuntor', 'entupir lâmpada', 'vazar pia', 'vazar vaso sanitário', 'vazar cano', 'vazar torneira', 'vazar chuveiro',
    'vazar tomada', 'vazar disjuntor', 'vazar lâmpada', 'estourar pia', 'estourar vaso sanitário', 'estourar cano', 'estourar torneira', 'estourar chuveiro',
    'estourar tomada', 'estourar disjuntor', 'estourar lâmpada', 'queimar pia', 'queimar vaso sanitário', 'queimar cano', 'queimar torneira', 'queimar chuveiro',
    'queimar tomada', 'queimar disjuntor', 'queimar lâmpada', 'curto-circuitar pia', 'curto-circuitar vaso sanitário', 'curto-circuitar cano', 'curto-circuitar torneira', 'curto-circuitar chuveiro',
    'curto-circuitar tomada', 'curto-circuitar disjuntor', 'curto-circuitar lâmpada', 'perder story', 'perder print', 'perder comentário', 'perder mensagem privada', 'perder e-mail errado',
    'perder arquivo errado', 'perder foto errada', 'perder vídeo errado', 'perder áudio errado', 'travar em story', 'travar em print', 'travar em comentário', 'travar em mensagem privada',
    'travar em e-mail errado', 'travar em arquivo errado', 'travar em foto errada', 'travar em vídeo errado', 'travar em áudio errado', 'postar por engano story', 'postar por engano print', 'postar por engano comentário',
    'postar por engano mensagem privada', 'postar por engano e-mail errado', 'postar por engano arquivo errado', 'postar por engano foto errada', 'postar por engano vídeo errado', 'postar por engano áudio errado', 'curtir por engano story', 'curtir por engano print',
    'curtir por engano comentário', 'curtir por engano mensagem privada', 'curtir por engano e-mail errado', 'curtir por engano arquivo errado', 'curtir por engano foto errada', 'curtir por engano vídeo errado', 'curtir por engano áudio errado', 'enviar por engano story',
  ],
};
