// Banco de perguntas, sempre na 1ª pessoa de quem está na Hot Seat.
const QUESTIONS = {
  leves: [
    'Qual é meu prato favorito?',
    'Qual é minha cor favorita?',
    'Qual é o filme que eu mais assisti na vida?',
    'Qual é meu animal favorito?',
    'Qual é minha estação do ano favorita?',
    'Qual é o lugar que eu mais quero conhecer?',
    'Qual é minha bebida favorita?',
    'Qual é o meu hobby favorito?',
    'Qual é a minha música favorita pra cantar no chuveiro?',
    'Qual é o meu doce favorito?',
    'Qual foi meu primeiro emprego?',
    'Qual é o meu esporte favorito pra assistir?',
    'Qual é o meu programa de TV ou série favorito?',
    'Qual é a minha fruta favorita?',
    'Qual é o meu dia da semana favorito?',
    'Qual é o meu super-herói favorito?',
    'Qual foi meu apelido de infância?',
    'Qual é a playlist que eu mais escuto?',
    'Qual é o meu sabor de sorvete favorito?',
    'Qual é o número que eu considero da sorte?',
  ],
  engracadas: [
    'Qual é minha maior mania esquisita?',
    'Qual foi a coisa mais idiota que já fiz por vergonha alheia de mim mesmo?',
    'Se eu fosse expulso de algum lugar, qual seria?',
    'Qual é o som que eu faço que mais incomoda os outros?',
    'Qual foi o apelido mais ridículo que já me deram?',
    'Se eu tivesse um superpoder inútil, qual seria?',
    'Qual é a coisa mais estranha que já comi?',
    'Qual foi a mentirinha boba que contei recentemente?',
    'Se eu virasse meme, qual seria a legenda?',
    'Qual foi o penteado mais vergonhoso que já tive?',
    'Qual foi a última coisa boba que me fez rir sozinho?',
    'Se eu fosse um personagem de desenho animado, quem seria?',
    'Qual é a minha dança mais ridícula?',
    'Qual foi a desculpa mais esfarrapada que já usei pra faltar em algo?',
    'Se eu ganhasse um troféu de "mais distraído", em que situação eu ganharia?',
    'Qual é a comida que eu finjo gostar mas não gosto?',
    'Qual foi a última vez que tropecei do nada?',
    'Se eu tivesse um bordão, qual seria?',
    'Qual é o emoji que mais me representa?',
    'Qual foi a roupa mais ridícula que já usei com orgulho?',
  ],
  bizarras: [
    'Se eu fosse um objeto da cozinha, qual seria?',
    'Se eu tivesse que comer a mesma coisa pro resto da vida, o que seria?',
    'Se eu virasse um animal por um dia, qual seria e o que faria?',
    'Qual é o lugar mais estranho onde eu já dormi?',
    'Se eu pudesse trocar de corpo com alguém por um dia, quem seria?',
    'Qual é a coisa mais estranha que guardo desde a infância?',
    'Se eu fosse um sabor de salgadinho, qual seria?',
    'Qual seria meu nome artístico se eu virasse cantor?',
    'Se eu tivesse que morar em outro país, qual seria e por quê?',
    'Qual é o cheiro mais estranho que eu gosto?',
    'Se eu fosse contratado pra um emprego bizarro, qual seria?',
    'Qual é o item mais inútil que eu já comprei?',
    'Se minha vida fosse um filme, qual seria o gênero?',
    'Qual seria minha última refeição se eu soubesse que era a última?',
    'Se eu pudesse ter qualquer poder sobrenatural por um dia, qual seria?',
    'Qual é o som mais estranho que eu já fiz achando que ninguém escutava?',
    'Se eu virasse um móvel da minha casa, qual seria?',
    'Qual é a teoria da conspiração mais boba que eu já acreditei?',
    'Se eu tivesse que escolher um tema pra minha festa de aniversário, qual seria?',
    'Qual é o hábito mais estranho que tenho e finjo que é normal?',
  ],
  desafiadoras: [
    'Qual foi minha mentirinha mais recente?',
    'Qual é a coisa que eu mais fico com ciúmes nos outros?',
    'Qual foi a última vez que menti pra sair de uma situação chata?',
    'Qual é meu maior medo bobo que eu escondo?',
    'Qual foi a maior vergonha que já passei em público?',
    'Qual é a coisa que eu mais reclamo mas nunca resolvo?',
    'Qual foi a última vez que fiquei com raiva de algo bobo?',
    'Qual é o segredinho bobo que eu escondo dos meus amigos?',
    'Qual foi a última compra por impulso que me arrependi?',
    'Qual é a coisa que eu mais procrastino?',
    'Qual foi a última vez que fingi estar ocupado pra evitar alguém?',
    'Qual é o hábito que eu sei que deveria largar mas não largo?',
    'Qual foi a última desculpa que dei pra não ir numa festa?',
    'Qual é a coisa que eu mais julgo nos outros mas também faço?',
    'Qual foi a última vez que chorei assistindo algo?',
    'Qual é o app que eu mais uso e sei que deveria usar menos?',
    'Qual foi a última promessa que fiz e não cumpri?',
    'Qual é a coisa mais boba pela qual eu já fiquei com inveja de alguém?',
    'Qual foi a última vez que fofoquei sobre alguém?',
    'Qual é a coisa que eu faço escondido que ninguém sabe?',
  ],
};
